// Auto-generated by tenant-publish.ts. DO NOT EDIT DIRECTLY.
import type { BusinessConfig } from '../../scripts/schema';

export const TENANTS_REGISTRY: Record<string, BusinessConfig> = {
  "aura-nail-bar": {
    "id": "22222222-2222-4222-8222-222222222222",
    "slug": "aura-nail-bar",
    "name": "AURA NAIL BAR",
    "status": "sample",
    "tagline": "Экспресс-студия маникюра и концептуальный нейл-бар",
    "phone": "+7 (812) 330-99-44",
    "address": "Невский проспект, 78",
    "city": "Санкт-Петербург",
    "timezone": "Europe/Moscow",
    "currency": "RUB",
    "minBookingNoticeMin": 45,
    "maxBookingHorizonDays": 21,
    "cancellationDeadlineHours": 3,
    "instructions": "Студия расположена на 2 этаже арт-пространства. Быстрая запись, высокоскоростной Wi-Fi, напитки to-go.",
    "theme": {
      "accentColor": "#2DD4BF",
      "secondaryAccentColor": "#F5EBE0",
      "bgColor": "#0F172A",
      "cardBgColor": "#1E293B",
      "borderColor": "rgba(255, 255, 255, 0.1)",
      "textColor": "#F8FAFC",
      "mutedColor": "#94A3B8",
      "fontHeading": "Inter, sans-serif",
      "fontBody": "Inter, sans-serif"
    },
    "infoCards": [
      {
        "id": "card-1",
        "title": "Работаем каждый день",
        "description": "С 10:00 до 22:00 без выходных и перерывов",
        "icon": "Clock"
      },
      {
        "id": "card-2",
        "title": "Опытные мастера",
        "description": "Сертифицированные специалисты с опытом от 5 лет",
        "icon": "Star"
      },
      {
        "id": "card-3",
        "title": "Материалы премиум-класса",
        "description": "Безопасные составы, стерилизация по СанПиН в 3 этапа",
        "icon": "ShieldCheck"
      }
    ],
    "businessHours": [
      {
        "dayOfWeek": 0,
        "openTime": "11:00",
        "closeTime": "21:00",
        "isClosed": false
      },
      {
        "dayOfWeek": 1,
        "openTime": "09:00",
        "closeTime": "22:00",
        "isClosed": false
      },
      {
        "dayOfWeek": 2,
        "openTime": "09:00",
        "closeTime": "22:00",
        "isClosed": false
      },
      {
        "dayOfWeek": 3,
        "openTime": "09:00",
        "closeTime": "22:00",
        "isClosed": false
      },
      {
        "dayOfWeek": 4,
        "openTime": "09:00",
        "closeTime": "22:00",
        "isClosed": false
      },
      {
        "dayOfWeek": 5,
        "openTime": "09:00",
        "closeTime": "23:00",
        "isClosed": false
      },
      {
        "dayOfWeek": 6,
        "openTime": "10:00",
        "closeTime": "22:00",
        "isClosed": false
      }
    ],
    "workplaces": [
      {
        "id": "20000000-0000-4000-8000-000000000001",
        "name": "Барная стойка Aura 1",
        "type": "MANICURE_DESK",
        "isActive": true
      },
      {
        "id": "20000000-0000-4000-8000-000000000002",
        "name": "Барная стойка Aura 2",
        "type": "MANICURE_DESK",
        "isActive": true
      },
      {
        "id": "20000000-0000-4000-8000-000000000003",
        "name": "Педикюрная капсула Podology",
        "type": "PEDICURE_CHAIR",
        "isActive": true
      }
    ],
    "categories": [
      {
        "id": "20000000-0000-4000-8000-000000000010",
        "name": "Экспресс-маникюр",
        "displayOrder": 1,
        "isActive": true
      },
      {
        "id": "20000000-0000-4000-8000-000000000020",
        "name": "Покрытие & Дизайн",
        "displayOrder": 2,
        "isActive": true
      },
      {
        "id": "20000000-0000-4000-8000-000000000030",
        "name": "Подология & Педикюр",
        "displayOrder": 3,
        "isActive": true
      }
    ],
    "services": [
      {
        "id": "20000000-0000-4000-8000-000000000101",
        "categoryId": "20000000-0000-4000-8000-000000000010",
        "name": "Скоростной экспресс-маникюр",
        "description": "Чистая аппаратная обработка за 40 минут. Идеально для занятых девушек в обеденный перерыв.",
        "price": 1800,
        "durationMin": 40,
        "bufferAfterMin": 10,
        "requiredWorkplaceType": "MANICURE_DESK",
        "imageUrl": "https://images.unsplash.com/photo-1632345031435-8727f6897d53?auto=format&fit=crop&w=600&q=80",
        "displayOrder": 1,
        "isActive": true
      },
      {
        "id": "20000000-0000-4000-8000-000000000102",
        "categoryId": "20000000-0000-4000-8000-000000000020",
        "name": "Маникюр с сияющим покрытием Flash Gel",
        "description": "Комби-обработка, светоотражающие трендовые базы Flash Disco с глубоким переливом.",
        "price": 2600,
        "durationMin": 70,
        "bufferAfterMin": 15,
        "requiredWorkplaceType": "MANICURE_DESK",
        "imageUrl": "https://images.unsplash.com/photo-1604654894610-df63bc536371?auto=format&fit=crop&w=600&q=80",
        "displayOrder": 2,
        "isActive": true
      },
      {
        "id": "20000000-0000-4000-8000-000000000103",
        "categoryId": "20000000-0000-4000-8000-000000000030",
        "name": "Кислотный экспресс-педикюр KART",
        "description": "Фруктово-ферментативная обработка сложных стоп и натоптышей без лезвий и трещин.",
        "price": 3500,
        "durationMin": 75,
        "bufferAfterMin": 15,
        "requiredWorkplaceType": "PEDICURE_CHAIR",
        "imageUrl": "https://images.unsplash.com/photo-1519415510236-718bdfcd89c8?auto=format&fit=crop&w=600&q=80",
        "displayOrder": 3,
        "isActive": true
      }
    ],
    "options": [
      {
        "id": "20000000-0000-4000-8000-000000000201",
        "name": "Снятие гель-лака",
        "description": "Быстрое снятие твердосплавной фрезой",
        "price": 350,
        "durationMin": 15,
        "bufferAfterMin": 0,
        "displayOrder": 1,
        "isActive": true
      },
      {
        "id": "20000000-0000-4000-8000-000000000202",
        "name": "Глянцевый топ анти-царапины",
        "description": "Сверхстойкий финиш с зеркальным блеском до 5 недель",
        "price": 300,
        "durationMin": 10,
        "bufferAfterMin": 0,
        "displayOrder": 2,
        "isActive": true
      }
    ],
    "masters": [
      {
        "id": "20000000-0000-4000-8000-000000000301",
        "name": "Диана Романова",
        "title": "Мастер-эксперт Aura Bar",
        "bio": "Опыт 4 года. Специалист по скоростному комбо-маникюру и ультра-глянцевому покрытию.",
        "avatarUrl": "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=400&q=80",
        "rating": 4.96,
        "reviewsCount": 112,
        "serviceIds": [
          "20000000-0000-4000-8000-000000000101",
          "20000000-0000-4000-8000-000000000102"
        ],
        "schedule": [
          {
            "dayOfWeek": 0,
            "startTime": "11:00",
            "endTime": "21:00",
            "isDayOff": false,
            "breaks": []
          },
          {
            "dayOfWeek": 1,
            "startTime": "09:00",
            "endTime": "22:00",
            "isDayOff": false,
            "breaks": []
          },
          {
            "dayOfWeek": 2,
            "startTime": "09:00",
            "endTime": "22:00",
            "isDayOff": false,
            "breaks": []
          },
          {
            "dayOfWeek": 3,
            "startTime": "09:00",
            "endTime": "22:00",
            "isDayOff": false,
            "breaks": []
          },
          {
            "dayOfWeek": 4,
            "startTime": "09:00",
            "endTime": "22:00",
            "isDayOff": false,
            "breaks": []
          },
          {
            "dayOfWeek": 5,
            "startTime": "09:00",
            "endTime": "22:00",
            "isDayOff": true,
            "breaks": []
          },
          {
            "dayOfWeek": 6,
            "startTime": "10:00",
            "endTime": "22:00",
            "isDayOff": true,
            "breaks": []
          }
        ],
        "breaks": [],
        "displayOrder": 1,
        "isActive": true
      },
      {
        "id": "20000000-0000-4000-8000-000000000302",
        "name": "Мария Лазарева",
        "title": "Подолог-эстетист",
        "bio": "Опыт 8 лет. Сложный медицинский педикюр, обработка стопы KART, установка коррекционных систем.",
        "avatarUrl": "https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=400&q=80",
        "rating": 4.99,
        "reviewsCount": 184,
        "serviceIds": [
          "20000000-0000-4000-8000-000000000101",
          "20000000-0000-4000-8000-000000000103"
        ],
        "schedule": [
          {
            "dayOfWeek": 0,
            "startTime": "11:00",
            "endTime": "21:00",
            "isDayOff": true,
            "breaks": []
          },
          {
            "dayOfWeek": 1,
            "startTime": "10:00",
            "endTime": "20:00",
            "isDayOff": false,
            "breaks": []
          },
          {
            "dayOfWeek": 2,
            "startTime": "10:00",
            "endTime": "20:00",
            "isDayOff": false,
            "breaks": []
          },
          {
            "dayOfWeek": 3,
            "startTime": "10:00",
            "endTime": "20:00",
            "isDayOff": false,
            "breaks": []
          },
          {
            "dayOfWeek": 4,
            "startTime": "10:00",
            "endTime": "20:00",
            "isDayOff": false,
            "breaks": []
          },
          {
            "dayOfWeek": 5,
            "startTime": "09:00",
            "endTime": "23:00",
            "isDayOff": false,
            "breaks": []
          },
          {
            "dayOfWeek": 6,
            "startTime": "10:00",
            "endTime": "22:00",
            "isDayOff": false,
            "breaks": []
          }
        ],
        "breaks": [],
        "displayOrder": 2,
        "isActive": true
      }
    ],
    "assets": {
      "logo": "https://images.unsplash.com/photo-1632345031435-8727f6897d53?auto=format&fit=crop&w=150&q=80",
      "hero": "https://images.unsplash.com/photo-1519014816548-bf5fe059798b?auto=format&fit=crop&w=1200&q=80",
      "gallery": [
        "https://images.unsplash.com/photo-1604654894610-df63bc536371?auto=format&fit=crop&w=600&q=80"
      ],
      "galleryItems": []
    }
  },
  "ayza-beauty-space": {
    "id": "33333333-3333-4333-8333-333333333333",
    "slug": "ayza-beauty-space",
    "name": "AYZA BEAUTY SPACE",
    "status": "published",
    "tagline": "Премиальное пространство красоты в Шымкенте · Макияж, волосы, ногти, ресницы и брови",
    "phone": "+7 (702) 386-71-76",
    "address": "проспект Нурсултана Назарбаева, 55/1",
    "city": "Шымкент",
    "timezone": "Asia/Almaty",
    "currency": "KZT",
    "minBookingNoticeMin": 45,
    "maxBookingHorizonDays": 30,
    "cancellationDeadlineHours": 3,
    "instructions": "Салон расположен по адресу пр. Нурсултана Назарбаева, 55/1 (район Нурсат). Гостевая парковка, Wi-Fi, комплиментарный кофе и авторский чай. Запись также в Instagram: @ayza.beauty.space.",
    "theme": {
      "accentColor": "#8E283E",
      "secondaryAccentColor": "#E8D5D8",
      "bgColor": "#080608",
      "cardBgColor": "#140E10",
      "borderColor": "rgba(142, 40, 62, 0.25)",
      "textColor": "#FFFFFF",
      "mutedColor": "#A8989B",
      "fontHeading": "'Playfair Display', Georgia, serif",
      "fontBody": "'Inter', -apple-system, sans-serif"
    },
    "infoCards": [
      {
        "id": "card-1",
        "title": "Ежедневно до 20:00",
        "description": "Работаем каждый день без выходных в районе Нурсат (пр. Назарбаева, 55/1)",
        "icon": "Clock"
      },
      {
        "id": "card-2",
        "title": "Top Master Ayza Ertaeva",
        "description": "Авторские свадебные и вечерние образы, сертифицированная команда топ-стилистов",
        "icon": "Star"
      },
      {
        "id": "card-3",
        "title": "Премиум-сервис & Халал",
        "description": "Стерилизация инструментов 100%, халал-коррекция и люксовые составы",
        "icon": "ShieldCheck"
      }
    ],
    "businessHours": [
      {
        "dayOfWeek": 0,
        "openTime": "09:00",
        "closeTime": "20:00",
        "isClosed": false
      },
      {
        "dayOfWeek": 1,
        "openTime": "09:00",
        "closeTime": "20:00",
        "isClosed": false
      },
      {
        "dayOfWeek": 2,
        "openTime": "09:00",
        "closeTime": "20:00",
        "isClosed": false
      },
      {
        "dayOfWeek": 3,
        "openTime": "09:00",
        "closeTime": "20:00",
        "isClosed": false
      },
      {
        "dayOfWeek": 4,
        "openTime": "09:00",
        "closeTime": "20:00",
        "isClosed": false
      },
      {
        "dayOfWeek": 5,
        "openTime": "09:00",
        "closeTime": "20:00",
        "isClosed": false
      },
      {
        "dayOfWeek": 6,
        "openTime": "09:00",
        "closeTime": "20:00",
        "isClosed": false
      }
    ],
    "workplaces": [
      {
        "id": "30000000-0000-4000-8000-000000000001",
        "name": "Студия визажа и укладок",
        "type": "UNIVERSAL",
        "isActive": true
      },
      {
        "id": "30000000-0000-4000-8000-000000000002",
        "name": "Маникюрная станция Ayza",
        "type": "MANICURE_DESK",
        "isActive": true
      },
      {
        "id": "30000000-0000-4000-8000-000000000003",
        "name": "Smart СПА-кресло педикюра",
        "type": "PEDICURE_CHAIR",
        "isActive": true
      },
      {
        "id": "30000000-0000-4000-8000-000000000004",
        "name": "Lash & Brow зона",
        "type": "UNIVERSAL",
        "isActive": true
      },
      {
        "id": "30000000-0000-4000-8000-000000000005",
        "name": "Кабинет шугаринга и депиляции",
        "type": "UNIVERSAL",
        "isActive": true
      }
    ],
    "categories": [
      {
        "id": "30000000-0000-4000-8000-000000000010",
        "name": "Make-Up & Hair",
        "displayOrder": 1,
        "isActive": true
      },
      {
        "id": "30000000-0000-4000-8000-000000000020",
        "name": "Nail (Маникюр)",
        "displayOrder": 2,
        "isActive": true
      },
      {
        "id": "30000000-0000-4000-8000-000000000030",
        "name": "Pedicure (Педикюр)",
        "displayOrder": 3,
        "isActive": true
      },
      {
        "id": "30000000-0000-4000-8000-000000000040",
        "name": "Lashes (Ресницы)",
        "displayOrder": 4,
        "isActive": true
      },
      {
        "id": "30000000-0000-4000-8000-000000000050",
        "name": "Brows (Брови)",
        "displayOrder": 5,
        "isActive": true
      },
      {
        "id": "30000000-0000-4000-8000-000000000060",
        "name": "Sugaring (Шугаринг)",
        "displayOrder": 6,
        "isActive": true
      }
    ],
    "services": [
      {
        "id": "30000000-0000-4000-8000-000000000101",
        "categoryId": "30000000-0000-4000-8000-000000000010",
        "name": "Образ от Top Master Ayza Ertaeva",
        "description": "Эксклюзивный полный образ от основательницы студии: авторский макияж и вечерняя прическа/укладка.",
        "price": 20000,
        "durationMin": 90,
        "bufferAfterMin": 15,
        "requiredWorkplaceType": "UNIVERSAL",
        "imageUrl": "/tenants/ayza-beauty-space/images/service-makeup-bridal.jpg",
        "displayOrder": 1,
        "isActive": true
      },
      {
        "id": "30000000-0000-4000-8000-000000000102",
        "categoryId": "30000000-0000-4000-8000-000000000010",
        "name": "Дневной макияж",
        "description": "Естественный сияющий макияж, деликатно подчеркивающий природную красоту.",
        "price": 9000,
        "durationMin": 60,
        "bufferAfterMin": 15,
        "requiredWorkplaceType": "UNIVERSAL",
        "imageUrl": "/tenants/ayza-beauty-space/images/service-makeup-day.jpg",
        "displayOrder": 2,
        "isActive": true
      },
      {
        "id": "30000000-0000-4000-8000-000000000103",
        "categoryId": "30000000-0000-4000-8000-000000000010",
        "name": "Вечерний макияж",
        "description": "Стойкий выразительный макияж для праздников, торжеств и фотосессий.",
        "price": 10000,
        "durationMin": 60,
        "bufferAfterMin": 15,
        "requiredWorkplaceType": "UNIVERSAL",
        "imageUrl": "/tenants/ayza-beauty-space/images/service-makeup-evening.jpg",
        "displayOrder": 3,
        "isActive": true
      },
      {
        "id": "30000000-0000-4000-8000-000000000104",
        "categoryId": "30000000-0000-4000-8000-000000000010",
        "name": "Свадебный макияж",
        "description": "Безупречный стойкий свадебный макияж, водостойкие премиальные текстуры.",
        "price": 12000,
        "durationMin": 90,
        "bufferAfterMin": 15,
        "requiredWorkplaceType": "UNIVERSAL",
        "imageUrl": "https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=600&q=80",
        "displayOrder": 4,
        "isActive": true
      },
      {
        "id": "30000000-0000-4000-8000-000000000105",
        "categoryId": "30000000-0000-4000-8000-000000000010",
        "name": "Женская стрижка",
        "description": "Стрижка по форме лица с мытьем головы и легкой укладкой.",
        "price": 6000,
        "durationMin": 45,
        "bufferAfterMin": 15,
        "requiredWorkplaceType": "UNIVERSAL",
        "imageUrl": "https://images.unsplash.com/photo-1560869713-7d0a29430803?auto=format&fit=crop&w=600&q=80",
        "displayOrder": 5,
        "isActive": true
      },
      {
        "id": "30000000-0000-4000-8000-000000000106",
        "categoryId": "30000000-0000-4000-8000-000000000010",
        "name": "Коррекция челки",
        "description": "Быстрое обновление и придание формы челке.",
        "price": 3000,
        "durationMin": 20,
        "bufferAfterMin": 10,
        "requiredWorkplaceType": "UNIVERSAL",
        "imageUrl": "https://images.unsplash.com/photo-1562322140-8baeececf3df?auto=format&fit=crop&w=600&q=80",
        "displayOrder": 6,
        "isActive": true
      },
      {
        "id": "30000000-0000-4000-8000-000000000107",
        "categoryId": "30000000-0000-4000-8000-000000000010",
        "name": "Укладка волос",
        "description": "Брашинг, струящиеся локоны или гладкий глянец.",
        "price": 6000,
        "durationMin": 45,
        "bufferAfterMin": 15,
        "requiredWorkplaceType": "UNIVERSAL",
        "imageUrl": "/tenants/ayza-beauty-space/images/service-hair-styling.jpg",
        "displayOrder": 7,
        "isActive": true
      },
      {
        "id": "30000000-0000-4000-8000-000000000108",
        "categoryId": "30000000-0000-4000-8000-000000000010",
        "name": "Прическа",
        "description": "Торжественная собранная прическа, текстурный пучок или хвост.",
        "price": 8000,
        "durationMin": 60,
        "bufferAfterMin": 15,
        "requiredWorkplaceType": "UNIVERSAL",
        "imageUrl": "/tenants/ayza-beauty-space/images/service-hair-evening.jpg",
        "displayOrder": 8,
        "isActive": true
      },
      {
        "id": "30000000-0000-4000-8000-000000000109",
        "categoryId": "30000000-0000-4000-8000-000000000010",
        "name": "Свадебная прическа",
        "description": "Королевская прическа невесты с надежной фиксацией фаты и аксессуаров.",
        "price": 15000,
        "durationMin": 90,
        "bufferAfterMin": 15,
        "requiredWorkplaceType": "UNIVERSAL",
        "imageUrl": "/tenants/ayza-beauty-space/images/service-hair-bridal.jpg",
        "displayOrder": 9,
        "isActive": true
      },
      {
        "id": "30000000-0000-4000-8000-000000000110",
        "categoryId": "30000000-0000-4000-8000-000000000010",
        "name": "Окрашивание корней волос",
        "description": "Качественное обновление цвета и закрашивание седины.",
        "price": 10000,
        "durationMin": 90,
        "bufferAfterMin": 15,
        "requiredWorkplaceType": "UNIVERSAL",
        "imageUrl": "https://images.unsplash.com/photo-1607746882042-944635dfe10e?auto=format&fit=crop&w=600&q=80",
        "displayOrder": 10,
        "isActive": true
      },
      {
        "id": "30000000-0000-4000-8000-000000000111",
        "categoryId": "30000000-0000-4000-8000-000000000010",
        "name": "Окрашивание тон в тон",
        "description": "Глубокий сияющий цвет по всей длине с сохранением шелковистости волос.",
        "price": 15000,
        "durationMin": 120,
        "bufferAfterMin": 15,
        "requiredWorkplaceType": "UNIVERSAL",
        "imageUrl": "https://images.unsplash.com/photo-1522337094346-297c5553e4c4?auto=format&fit=crop&w=600&q=80",
        "displayOrder": 11,
        "isActive": true
      },
      {
        "id": "30000000-0000-4000-8000-000000000112",
        "categoryId": "30000000-0000-4000-8000-000000000010",
        "name": "Сложное окрашивание",
        "description": "Airtouch, Balayage, Шатуш — плавные переливы и премиальный блонд.",
        "price": 30000,
        "durationMin": 180,
        "bufferAfterMin": 20,
        "requiredWorkplaceType": "UNIVERSAL",
        "imageUrl": "https://images.unsplash.com/photo-1595476108010-b4d1f102b1b1?auto=format&fit=crop&w=600&q=80",
        "displayOrder": 12,
        "isActive": true
      },
      {
        "id": "30000000-0000-4000-8000-000000000201",
        "categoryId": "30000000-0000-4000-8000-000000000020",
        "name": "Маникюр",
        "description": "Аппаратная или комбинированная обработка кутикулы и формы ногтей.",
        "price": 5000,
        "durationMin": 45,
        "bufferAfterMin": 15,
        "requiredWorkplaceType": "MANICURE_DESK",
        "imageUrl": "/tenants/ayza-beauty-space/images/service-manicure-classic.jpg",
        "displayOrder": 1,
        "isActive": true
      },
      {
        "id": "30000000-0000-4000-8000-000000000202",
        "categoryId": "30000000-0000-4000-8000-000000000020",
        "name": "Маникюр + лак покрытие",
        "description": "Чистый гигиенический маникюр со стойким глянцевым лаковым покрытием.",
        "price": 8000,
        "durationMin": 60,
        "bufferAfterMin": 15,
        "requiredWorkplaceType": "MANICURE_DESK",
        "imageUrl": "/tenants/ayza-beauty-space/images/service-manicure-polish.jpg",
        "displayOrder": 2,
        "isActive": true
      },
      {
        "id": "30000000-0000-4000-8000-000000000203",
        "categoryId": "30000000-0000-4000-8000-000000000020",
        "name": "Наращивание ногтей на верхних формах",
        "description": "Современное моделирование: идеальная форма и тонкий натуральный торец.",
        "price": 10000,
        "durationMin": 120,
        "bufferAfterMin": 15,
        "requiredWorkplaceType": "MANICURE_DESK",
        "imageUrl": "/tenants/ayza-beauty-space/images/service-manicure-extension.jpg",
        "displayOrder": 3,
        "isActive": true
      },
      {
        "id": "30000000-0000-4000-8000-000000000204",
        "categoryId": "30000000-0000-4000-8000-000000000020",
        "name": "Наращивание ногтей на нижних формах",
        "description": "Классическое наращивание любой длины под кутикулу.",
        "price": 11000,
        "durationMin": 120,
        "bufferAfterMin": 15,
        "requiredWorkplaceType": "MANICURE_DESK",
        "imageUrl": "https://images.unsplash.com/photo-1571290274554-6a2eaa771e5f?auto=format&fit=crop&w=600&q=80",
        "displayOrder": 4,
        "isActive": true
      },
      {
        "id": "30000000-0000-4000-8000-000000000205",
        "categoryId": "30000000-0000-4000-8000-000000000020",
        "name": "Японский маникюр",
        "description": "Эко-глянцевание минеральной пастой и жемчужной пудрой Masura.",
        "price": 10000,
        "durationMin": 60,
        "bufferAfterMin": 15,
        "requiredWorkplaceType": "MANICURE_DESK",
        "imageUrl": "https://images.unsplash.com/photo-1566113519662-7807a42cc50d?auto=format&fit=crop&w=600&q=80",
        "displayOrder": 5,
        "isActive": true
      },
      {
        "id": "30000000-0000-4000-8000-000000000301",
        "categoryId": "30000000-0000-4000-8000-000000000030",
        "name": "Педикюр",
        "description": "Классическая гигиеническая обработка стоп и аккуратная форма пальчиков.",
        "price": 8000,
        "durationMin": 60,
        "bufferAfterMin": 15,
        "requiredWorkplaceType": "PEDICURE_CHAIR",
        "imageUrl": "/tenants/ayza-beauty-space/images/service-pedicure-classic.jpg",
        "displayOrder": 1,
        "isActive": true
      },
      {
        "id": "30000000-0000-4000-8000-000000000302",
        "categoryId": "30000000-0000-4000-8000-000000000030",
        "name": "Педикюр с гелевым покрытием",
        "description": "Гигиенический педикюр с нанесением стойкого цветного гель-лака.",
        "price": 10000,
        "durationMin": 75,
        "bufferAfterMin": 15,
        "requiredWorkplaceType": "PEDICURE_CHAIR",
        "imageUrl": "/tenants/ayza-beauty-space/images/service-pedicure-gel.jpg",
        "displayOrder": 2,
        "isActive": true
      },
      {
        "id": "30000000-0000-4000-8000-000000000303",
        "categoryId": "30000000-0000-4000-8000-000000000030",
        "name": "Smart педикюр без покрытия",
        "description": "Аппаратная шлифовка стоп smart-дисками до зеркальной мягкости.",
        "price": 9000,
        "durationMin": 60,
        "bufferAfterMin": 15,
        "requiredWorkplaceType": "PEDICURE_CHAIR",
        "imageUrl": "https://images.unsplash.com/photo-1519415510236-718bdfcd89c8?auto=format&fit=crop&w=600&q=80",
        "displayOrder": 3,
        "isActive": true
      },
      {
        "id": "30000000-0000-4000-8000-000000000304",
        "categoryId": "30000000-0000-4000-8000-000000000030",
        "name": "Smart педикюр с гель лак покрытием",
        "description": "Smart-обработка стоп молекулярным маслом + покрытие гель-лаком.",
        "price": 10000,
        "durationMin": 75,
        "bufferAfterMin": 15,
        "requiredWorkplaceType": "PEDICURE_CHAIR",
        "imageUrl": "https://images.unsplash.com/photo-1508746829417-e6f548d8d6ed?auto=format&fit=crop&w=600&q=80",
        "displayOrder": 4,
        "isActive": true
      },
      {
        "id": "30000000-0000-4000-8000-000000000305",
        "categoryId": "30000000-0000-4000-8000-000000000030",
        "name": "Комбинированный педикюр",
        "description": "Аппаратный и препаратный уход для нежной кожи стоп.",
        "price": 9000,
        "durationMin": 60,
        "bufferAfterMin": 15,
        "requiredWorkplaceType": "PEDICURE_CHAIR",
        "imageUrl": "https://images.unsplash.com/photo-1516914943479-89db7d9ae7f2?auto=format&fit=crop&w=600&q=80",
        "displayOrder": 5,
        "isActive": true
      },
      {
        "id": "30000000-0000-4000-8000-000000000306",
        "categoryId": "30000000-0000-4000-8000-000000000030",
        "name": "Комбинированный педикюр с гель лак покрытием",
        "description": "Комбинированная эстетика стоп и стойкое стойкое покрытие.",
        "price": 10000,
        "durationMin": 75,
        "bufferAfterMin": 15,
        "requiredWorkplaceType": "PEDICURE_CHAIR",
        "imageUrl": "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&w=600&q=80",
        "displayOrder": 6,
        "isActive": true
      },
      {
        "id": "30000000-0000-4000-8000-000000000307",
        "categoryId": "30000000-0000-4000-8000-000000000030",
        "name": "Японский педикюр",
        "description": "Премиальное эко-восстановление ногтевой пластины и стоп.",
        "price": 12000,
        "durationMin": 75,
        "bufferAfterMin": 15,
        "requiredWorkplaceType": "PEDICURE_CHAIR",
        "imageUrl": "https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=600&q=80",
        "displayOrder": 7,
        "isActive": true
      },
      {
        "id": "30000000-0000-4000-8000-000000000308",
        "categoryId": "30000000-0000-4000-8000-000000000030",
        "name": "Спа процедура скрабирование + парафин + питательный крем",
        "description": "Роскошный СПА-ритуал для мягкости и шелковистости ваших ножек.",
        "price": 2000,
        "durationMin": 30,
        "bufferAfterMin": 10,
        "requiredWorkplaceType": "PEDICURE_CHAIR",
        "imageUrl": "/tenants/ayza-beauty-space/images/service-pedicure-spa.jpg",
        "displayOrder": 8,
        "isActive": true
      },
      {
        "id": "30000000-0000-4000-8000-000000000401",
        "categoryId": "30000000-0000-4000-8000-000000000040",
        "name": "Классика",
        "description": "Наращивание одной искусственной ресницы на каждую свою (1D).",
        "price": 8000,
        "durationMin": 90,
        "bufferAfterMin": 15,
        "requiredWorkplaceType": "UNIVERSAL",
        "imageUrl": "/tenants/ayza-beauty-space/images/service-lashes-classic.jpg",
        "displayOrder": 1,
        "isActive": true
      },
      {
        "id": "30000000-0000-4000-8000-000000000402",
        "categoryId": "30000000-0000-4000-8000-000000000040",
        "name": "Объем 2D-3D",
        "description": "Пышный бархатный объем, подчеркивающий глубину взгляда.",
        "price": 9000,
        "durationMin": 120,
        "bufferAfterMin": 15,
        "requiredWorkplaceType": "UNIVERSAL",
        "imageUrl": "https://images.unsplash.com/photo-1583001931096-959e9a1a6223?auto=format&fit=crop&w=600&q=80",
        "displayOrder": 2,
        "isActive": true
      },
      {
        "id": "30000000-0000-4000-8000-000000000403",
        "categoryId": "30000000-0000-4000-8000-000000000040",
        "name": "Объем 4D-5D",
        "description": "Роскошный мега-объем ультратонкими невесомыми ресничками.",
        "price": 10000,
        "durationMin": 120,
        "bufferAfterMin": 15,
        "requiredWorkplaceType": "UNIVERSAL",
        "imageUrl": "https://images.unsplash.com/photo-1512496015851-a90fb38ba796?auto=format&fit=crop&w=600&q=80",
        "displayOrder": 3,
        "isActive": true
      },
      {
        "id": "30000000-0000-4000-8000-000000000404",
        "categoryId": "30000000-0000-4000-8000-000000000040",
        "name": "Ламинирование ресниц",
        "description": "Удлинение, изгиб, глубокий черный цвет и питание витаминами.",
        "price": 8000,
        "durationMin": 60,
        "bufferAfterMin": 15,
        "requiredWorkplaceType": "UNIVERSAL",
        "imageUrl": "https://images.unsplash.com/photo-1522337660859-02fbefca4702?auto=format&fit=crop&w=600&q=80",
        "displayOrder": 4,
        "isActive": true
      },
      {
        "id": "30000000-0000-4000-8000-000000000501",
        "categoryId": "30000000-0000-4000-8000-000000000050",
        "name": "Коррекция бровей",
        "description": "Создание идеальной гармоничной формы пинцетом и воском.",
        "price": 3000,
        "durationMin": 30,
        "bufferAfterMin": 10,
        "requiredWorkplaceType": "UNIVERSAL",
        "imageUrl": "/tenants/ayza-beauty-space/images/service-brows.png",
        "displayOrder": 1,
        "isActive": true
      },
      {
        "id": "30000000-0000-4000-8000-000000000502",
        "categoryId": "30000000-0000-4000-8000-000000000050",
        "name": "Коррекция бровей + окрашивание",
        "description": "Архитектура формы и стойкое окрашивание премиум-хной или краской.",
        "price": 4500,
        "durationMin": 45,
        "bufferAfterMin": 15,
        "requiredWorkplaceType": "UNIVERSAL",
        "imageUrl": "https://images.unsplash.com/photo-1596704017254-9b121068fb31?auto=format&fit=crop&w=600&q=80",
        "displayOrder": 2,
        "isActive": true
      },
      {
        "id": "30000000-0000-4000-8000-000000000503",
        "categoryId": "30000000-0000-4000-8000-000000000050",
        "name": "Ламинирование бровей",
        "description": "Долговременная фиксация формы и кератиновое наполнение.",
        "price": 8000,
        "durationMin": 60,
        "bufferAfterMin": 15,
        "requiredWorkplaceType": "UNIVERSAL",
        "imageUrl": "https://images.unsplash.com/photo-1616683693504-3ea7e9ad6fec?auto=format&fit=crop&w=600&q=80",
        "displayOrder": 3,
        "isActive": true
      },
      {
        "id": "30000000-0000-4000-8000-000000000504",
        "categoryId": "30000000-0000-4000-8000-000000000050",
        "name": "Ламинирование бровей + окрашивание",
        "description": "Полный комплекс: ламинирование, коррекция формы и окрашивание.",
        "price": 9000,
        "durationMin": 60,
        "bufferAfterMin": 15,
        "requiredWorkplaceType": "UNIVERSAL",
        "imageUrl": "https://images.unsplash.com/photo-1588510849445-4795b277a454?auto=format&fit=crop&w=600&q=80",
        "displayOrder": 4,
        "isActive": true
      },
      {
        "id": "30000000-0000-4000-8000-000000000505",
        "categoryId": "30000000-0000-4000-8000-000000000050",
        "name": "Халал коррекция",
        "description": "Деликатное прореживание и оформление бровей строго по канонам Халал.",
        "price": 4000,
        "durationMin": 30,
        "bufferAfterMin": 10,
        "requiredWorkplaceType": "UNIVERSAL",
        "imageUrl": "https://images.unsplash.com/photo-1560066984-138dadb4c035?auto=format&fit=crop&w=600&q=80",
        "displayOrder": 5,
        "isActive": true
      },
      {
        "id": "30000000-0000-4000-8000-000000000601",
        "categoryId": "30000000-0000-4000-8000-000000000060",
        "name": "Лицо",
        "description": "Деликатное удаление пушковых волос на лице сахарной пастой.",
        "price": 4000,
        "durationMin": 20,
        "bufferAfterMin": 10,
        "requiredWorkplaceType": "UNIVERSAL",
        "imageUrl": "https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?auto=format&fit=crop&w=600&q=80",
        "displayOrder": 1,
        "isActive": true
      },
      {
        "id": "30000000-0000-4000-8000-000000000602",
        "categoryId": "30000000-0000-4000-8000-000000000060",
        "name": "Усики",
        "description": "Быстрое и безболезненное удаление волосков над верхней губой.",
        "price": 1500,
        "durationMin": 15,
        "bufferAfterMin": 5,
        "requiredWorkplaceType": "UNIVERSAL",
        "imageUrl": "https://images.unsplash.com/photo-1516975080664-ed2fc6a32937?auto=format&fit=crop&w=600&q=80",
        "displayOrder": 2,
        "isActive": true
      },
      {
        "id": "30000000-0000-4000-8000-000000000603",
        "categoryId": "30000000-0000-4000-8000-000000000060",
        "name": "Баки",
        "description": "Аккуратное оформление височной зоны.",
        "price": 2000,
        "durationMin": 15,
        "bufferAfterMin": 5,
        "requiredWorkplaceType": "UNIVERSAL",
        "imageUrl": "https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?auto=format&fit=crop&w=600&q=80",
        "displayOrder": 3,
        "isActive": true
      },
      {
        "id": "30000000-0000-4000-8000-000000000604",
        "categoryId": "30000000-0000-4000-8000-000000000060",
        "name": "Подмышечные впадины",
        "description": "Чистая гладкая кожа без раздражения и вросших волос.",
        "price": 2500,
        "durationMin": 20,
        "bufferAfterMin": 10,
        "requiredWorkplaceType": "UNIVERSAL",
        "imageUrl": "https://images.unsplash.com/photo-1515377905703-c4788e51af15?auto=format&fit=crop&w=600&q=80",
        "displayOrder": 4,
        "isActive": true
      },
      {
        "id": "30000000-0000-4000-8000-000000000605",
        "categoryId": "30000000-0000-4000-8000-000000000060",
        "name": "Глубокое бикини",
        "description": "Бережная процедура с использованием мягких антистресс-паст.",
        "price": 5000,
        "durationMin": 30,
        "bufferAfterMin": 15,
        "requiredWorkplaceType": "UNIVERSAL",
        "imageUrl": "https://images.unsplash.com/photo-1507652313519-d4e9174996dd?auto=format&fit=crop&w=600&q=80",
        "displayOrder": 5,
        "isActive": true
      },
      {
        "id": "30000000-0000-4000-8000-000000000606",
        "categoryId": "30000000-0000-4000-8000-000000000060",
        "name": "Руки до локтя",
        "description": "Шугаринг предплечий с успокаивающим лосьоном.",
        "price": 3000,
        "durationMin": 20,
        "bufferAfterMin": 10,
        "requiredWorkplaceType": "UNIVERSAL",
        "imageUrl": "https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?auto=format&fit=crop&w=600&q=80",
        "displayOrder": 6,
        "isActive": true
      },
      {
        "id": "30000000-0000-4000-8000-000000000607",
        "categoryId": "30000000-0000-4000-8000-000000000060",
        "name": "Руки полностью",
        "description": "Полная депиляция рук сахарной пастой премиум-класса.",
        "price": 5000,
        "durationMin": 30,
        "bufferAfterMin": 10,
        "requiredWorkplaceType": "UNIVERSAL",
        "imageUrl": "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=600&q=80",
        "displayOrder": 7,
        "isActive": true
      },
      {
        "id": "30000000-0000-4000-8000-000000000608",
        "categoryId": "30000000-0000-4000-8000-000000000060",
        "name": "Ноги до колен",
        "description": "Гладкость голеней и коленей до 4 недель.",
        "price": 3500,
        "durationMin": 25,
        "bufferAfterMin": 10,
        "requiredWorkplaceType": "UNIVERSAL",
        "imageUrl": "https://images.unsplash.com/photo-1513094735237-8f2714d57c13?auto=format&fit=crop&w=600&q=80",
        "displayOrder": 8,
        "isActive": true
      },
      {
        "id": "30000000-0000-4000-8000-000000000609",
        "categoryId": "30000000-0000-4000-8000-000000000060",
        "name": "Ноги полностью",
        "description": "Шугаринг ножек по всей длине с увлажняющим уходом.",
        "price": 6000,
        "durationMin": 40,
        "bufferAfterMin": 15,
        "requiredWorkplaceType": "UNIVERSAL",
        "imageUrl": "https://images.unsplash.com/photo-1498842812179-c81beecf902c?auto=format&fit=crop&w=600&q=80",
        "displayOrder": 9,
        "isActive": true
      },
      {
        "id": "30000000-0000-4000-8000-000000000610",
        "categoryId": "30000000-0000-4000-8000-000000000060",
        "name": "Живот",
        "description": "Деликатное удаление волосков в области живота.",
        "price": 2000,
        "durationMin": 20,
        "bufferAfterMin": 10,
        "requiredWorkplaceType": "UNIVERSAL",
        "imageUrl": "https://images.unsplash.com/photo-1519735777090-ec97162dc266?auto=format&fit=crop&w=600&q=80",
        "displayOrder": 10,
        "isActive": true
      },
      {
        "id": "30000000-0000-4000-8000-000000000611",
        "categoryId": "30000000-0000-4000-8000-000000000060",
        "name": "Спина",
        "description": "Шугаринг зоны спины гипоаллергенной пастой.",
        "price": 4000,
        "durationMin": 30,
        "bufferAfterMin": 10,
        "requiredWorkplaceType": "UNIVERSAL",
        "imageUrl": "https://images.unsplash.com/photo-1544161515-4ab6ce6db874?auto=format&fit=crop&w=600&q=80",
        "displayOrder": 11,
        "isActive": true
      }
    ],
    "options": [
      {
        "id": "30000000-0000-4000-8000-000000000701",
        "name": "Дизайн ногтей",
        "description": "Стильный авторский арт, френч или градиент",
        "price": 1000,
        "durationMin": 15,
        "bufferAfterMin": 0,
        "displayOrder": 1,
        "isActive": true
      },
      {
        "id": "30000000-0000-4000-8000-000000000702",
        "name": "Снятие гель-лака",
        "description": "Бережное аппаратное снятие старого покрытия",
        "price": 1000,
        "durationMin": 15,
        "bufferAfterMin": 0,
        "displayOrder": 2,
        "isActive": true
      },
      {
        "id": "30000000-0000-4000-8000-000000000703",
        "name": "Снятие наращенных ногтей",
        "description": "Атравматичное спиливание искусственного материала",
        "price": 1000,
        "durationMin": 20,
        "bufferAfterMin": 0,
        "displayOrder": 3,
        "isActive": true
      },
      {
        "id": "30000000-0000-4000-8000-000000000704",
        "name": "Воском (доплата)",
        "description": "Использование горячего полимерного воска вместо сахарной пасты",
        "price": 1000,
        "durationMin": 10,
        "bufferAfterMin": 0,
        "displayOrder": 4,
        "isActive": true
      },
      {
        "id": "30000000-0000-4000-8000-000000000705",
        "name": "Коричневые ресницы (Шоколад)",
        "description": "Мягкий благородный шоколадный оттенок для натурального взгляда",
        "price": 1000,
        "durationMin": 0,
        "bufferAfterMin": 0,
        "displayOrder": 5,
        "isActive": true
      },
      {
        "id": "30000000-0000-4000-8000-000000000706",
        "name": "Снятие ресниц",
        "description": "Безопасное снятие ресниц мягким кремовым ремувером",
        "price": 1000,
        "durationMin": 15,
        "bufferAfterMin": 0,
        "displayOrder": 6,
        "isActive": true
      },
      {
        "id": "30000000-0000-4000-8000-000000000707",
        "name": "Мокрый эффект (Wet Look)",
        "description": "Трендовый эффект нераскрытых ресничек",
        "price": 1000,
        "durationMin": 0,
        "bufferAfterMin": 0,
        "displayOrder": 7,
        "isActive": true
      },
      {
        "id": "30000000-0000-4000-8000-000000000708",
        "name": "Kylie эффект (Лучики)",
        "description": "Длинные акцентные лучи для дерзкого и выразительного взгляда",
        "price": 1000,
        "durationMin": 0,
        "bufferAfterMin": 0,
        "displayOrder": 8,
        "isActive": true
      },
      {
        "id": "30000000-0000-4000-8000-000000000709",
        "name": "Изгибы M, L, D, C",
        "description": "Выбор индивидуального изгиба ресниц",
        "price": 1000,
        "durationMin": 0,
        "bufferAfterMin": 0,
        "displayOrder": 9,
        "isActive": true
      },
      {
        "id": "30000000-0000-4000-8000-000000000710",
        "name": "Коррекция ресниц",
        "description": "Восстановление ресничного ряда до идеального состояния",
        "price": 5000,
        "durationMin": 60,
        "bufferAfterMin": 10,
        "displayOrder": 10,
        "isActive": true
      }
    ],
    "masters": [
      {
        "id": "30000000-0000-4000-8000-000000000801",
        "name": "Ayza Ertaeva",
        "title": "Основательница & Top Master",
        "bio": "Создательница пространства Ayza Beauty Space. Эксперт по свадебным и вечерним образам, сложным прическам и премиальному визажу.",
        "avatarUrl": "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80",
        "rating": 5,
        "reviewsCount": 164,
        "serviceIds": [
          "30000000-0000-4000-8000-000000000101",
          "30000000-0000-4000-8000-000000000102",
          "30000000-0000-4000-8000-000000000103",
          "30000000-0000-4000-8000-000000000104",
          "30000000-0000-4000-8000-000000000105",
          "30000000-0000-4000-8000-000000000106",
          "30000000-0000-4000-8000-000000000107",
          "30000000-0000-4000-8000-000000000108",
          "30000000-0000-4000-8000-000000000109",
          "30000000-0000-4000-8000-000000000110",
          "30000000-0000-4000-8000-000000000111",
          "30000000-0000-4000-8000-000000000112"
        ],
        "schedule": [
          {
            "dayOfWeek": 0,
            "startTime": "09:00",
            "endTime": "20:00",
            "isDayOff": false,
            "breaks": []
          },
          {
            "dayOfWeek": 1,
            "startTime": "09:00",
            "endTime": "20:00",
            "isDayOff": false,
            "breaks": []
          },
          {
            "dayOfWeek": 2,
            "startTime": "09:00",
            "endTime": "20:00",
            "isDayOff": false,
            "breaks": []
          },
          {
            "dayOfWeek": 3,
            "startTime": "09:00",
            "endTime": "20:00",
            "isDayOff": false,
            "breaks": []
          },
          {
            "dayOfWeek": 4,
            "startTime": "09:00",
            "endTime": "20:00",
            "isDayOff": false,
            "breaks": []
          },
          {
            "dayOfWeek": 5,
            "startTime": "09:00",
            "endTime": "20:00",
            "isDayOff": false,
            "breaks": []
          },
          {
            "dayOfWeek": 6,
            "startTime": "09:00",
            "endTime": "20:00",
            "isDayOff": false,
            "breaks": []
          }
        ],
        "breaks": [],
        "displayOrder": 1,
        "isActive": true
      },
      {
        "id": "30000000-0000-4000-8000-000000000802",
        "name": "Диана",
        "title": "Ведущий мастер ногтевого сервиса",
        "bio": "Опыт более 5 лет. Эксперт по Smart-педикюру, японскому уходу Masura и безупречному наращиванию ногтей.",
        "avatarUrl": "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=400&q=80",
        "rating": 4.98,
        "reviewsCount": 98,
        "serviceIds": [
          "30000000-0000-4000-8000-000000000201",
          "30000000-0000-4000-8000-000000000202",
          "30000000-0000-4000-8000-000000000203",
          "30000000-0000-4000-8000-000000000204",
          "30000000-0000-4000-8000-000000000205",
          "30000000-0000-4000-8000-000000000301",
          "30000000-0000-4000-8000-000000000302",
          "30000000-0000-4000-8000-000000000303",
          "30000000-0000-4000-8000-000000000304",
          "30000000-0000-4000-8000-000000000305",
          "30000000-0000-4000-8000-000000000306",
          "30000000-0000-4000-8000-000000000307",
          "30000000-0000-4000-8000-000000000308"
        ],
        "schedule": [
          {
            "dayOfWeek": 0,
            "startTime": "09:00",
            "endTime": "20:00",
            "isDayOff": false,
            "breaks": []
          },
          {
            "dayOfWeek": 1,
            "startTime": "09:00",
            "endTime": "20:00",
            "isDayOff": false,
            "breaks": []
          },
          {
            "dayOfWeek": 2,
            "startTime": "09:00",
            "endTime": "20:00",
            "isDayOff": false,
            "breaks": []
          },
          {
            "dayOfWeek": 3,
            "startTime": "09:00",
            "endTime": "20:00",
            "isDayOff": false,
            "breaks": []
          },
          {
            "dayOfWeek": 4,
            "startTime": "09:00",
            "endTime": "20:00",
            "isDayOff": false,
            "breaks": []
          },
          {
            "dayOfWeek": 5,
            "startTime": "09:00",
            "endTime": "20:00",
            "isDayOff": false,
            "breaks": []
          },
          {
            "dayOfWeek": 6,
            "startTime": "09:00",
            "endTime": "20:00",
            "isDayOff": false,
            "breaks": []
          }
        ],
        "breaks": [],
        "displayOrder": 2,
        "isActive": true
      },
      {
        "id": "30000000-0000-4000-8000-000000000803",
        "name": "Алина",
        "title": "Lash & Brow стилист",
        "bio": "Специалист по естественному наращиванию ресниц (Kylie, мокрый эффект), ламинированию и халал-коррекции бровей.",
        "avatarUrl": "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=400&q=80",
        "rating": 4.96,
        "reviewsCount": 85,
        "serviceIds": [
          "30000000-0000-4000-8000-000000000401",
          "30000000-0000-4000-8000-000000000402",
          "30000000-0000-4000-8000-000000000403",
          "30000000-0000-4000-8000-000000000404",
          "30000000-0000-4000-8000-000000000501",
          "30000000-0000-4000-8000-000000000502",
          "30000000-0000-4000-8000-000000000503",
          "30000000-0000-4000-8000-000000000504",
          "30000000-0000-4000-8000-000000000505"
        ],
        "schedule": [
          {
            "dayOfWeek": 0,
            "startTime": "09:00",
            "endTime": "20:00",
            "isDayOff": false,
            "breaks": []
          },
          {
            "dayOfWeek": 1,
            "startTime": "09:00",
            "endTime": "20:00",
            "isDayOff": false,
            "breaks": []
          },
          {
            "dayOfWeek": 2,
            "startTime": "09:00",
            "endTime": "20:00",
            "isDayOff": false,
            "breaks": []
          },
          {
            "dayOfWeek": 3,
            "startTime": "09:00",
            "endTime": "20:00",
            "isDayOff": false,
            "breaks": []
          },
          {
            "dayOfWeek": 4,
            "startTime": "09:00",
            "endTime": "20:00",
            "isDayOff": false,
            "breaks": []
          },
          {
            "dayOfWeek": 5,
            "startTime": "09:00",
            "endTime": "20:00",
            "isDayOff": false,
            "breaks": []
          },
          {
            "dayOfWeek": 6,
            "startTime": "09:00",
            "endTime": "20:00",
            "isDayOff": false,
            "breaks": []
          }
        ],
        "breaks": [],
        "displayOrder": 3,
        "isActive": true
      },
      {
        "id": "30000000-0000-4000-8000-000000000804",
        "name": "Камила",
        "title": "Мастер депиляции и шугаринга",
        "bio": "Деликатная и безболезненная техника шугаринга и восковой депиляции. Профессиональный спа-уход за кожей.",
        "avatarUrl": "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=400&q=80",
        "rating": 4.97,
        "reviewsCount": 72,
        "serviceIds": [
          "30000000-0000-4000-8000-000000000601",
          "30000000-0000-4000-8000-000000000602",
          "30000000-0000-4000-8000-000000000603",
          "30000000-0000-4000-8000-000000000604",
          "30000000-0000-4000-8000-000000000605",
          "30000000-0000-4000-8000-000000000606",
          "30000000-0000-4000-8000-000000000607",
          "30000000-0000-4000-8000-000000000608",
          "30000000-0000-4000-8000-000000000609",
          "30000000-0000-4000-8000-000000000610",
          "30000000-0000-4000-8000-000000000611"
        ],
        "schedule": [
          {
            "dayOfWeek": 0,
            "startTime": "09:00",
            "endTime": "20:00",
            "isDayOff": false,
            "breaks": []
          },
          {
            "dayOfWeek": 1,
            "startTime": "09:00",
            "endTime": "20:00",
            "isDayOff": false,
            "breaks": []
          },
          {
            "dayOfWeek": 2,
            "startTime": "09:00",
            "endTime": "20:00",
            "isDayOff": false,
            "breaks": []
          },
          {
            "dayOfWeek": 3,
            "startTime": "09:00",
            "endTime": "20:00",
            "isDayOff": false,
            "breaks": []
          },
          {
            "dayOfWeek": 4,
            "startTime": "09:00",
            "endTime": "20:00",
            "isDayOff": false,
            "breaks": []
          },
          {
            "dayOfWeek": 5,
            "startTime": "09:00",
            "endTime": "20:00",
            "isDayOff": false,
            "breaks": []
          },
          {
            "dayOfWeek": 6,
            "startTime": "09:00",
            "endTime": "20:00",
            "isDayOff": false,
            "breaks": []
          }
        ],
        "breaks": [],
        "displayOrder": 4,
        "isActive": true
      }
    ],
    "assets": {
      "logo": "/tenants/ayza-beauty-space/images/logo.jpg",
      "hero": "/tenants/ayza-beauty-space/images/hero.jpg",
      "gallery": [
        "/tenants/ayza-beauty-space/images/service-makeup-bridal.jpg",
        "/tenants/ayza-beauty-space/images/service-hair-bridal.jpg",
        "/tenants/ayza-beauty-space/images/service-manicure-extension.jpg",
        "/tenants/ayza-beauty-space/images/service-pedicure-gel.jpg",
        "/tenants/ayza-beauty-space/images/service-makeup-evening.jpg",
        "/tenants/ayza-beauty-space/images/service-hair-evening.jpg",
        "/tenants/ayza-beauty-space/images/service-brows.png",
        "/tenants/ayza-beauty-space/images/service-hair-styling.jpg",
        "/tenants/ayza-beauty-space/images/service-manicure-polish.jpg",
        "/tenants/ayza-beauty-space/images/service-pedicure-classic.jpg",
        "/tenants/ayza-beauty-space/images/service-lashes-classic.jpg",
        "/tenants/ayza-beauty-space/images/service-makeup-day.jpg",
        "/tenants/ayza-beauty-space/images/service-manicure-classic.jpg",
        "/tenants/ayza-beauty-space/images/service-pedicure-spa.jpg"
      ],
      "galleryItems": [
        {
          "id": "work-1",
          "imageUrl": "/tenants/ayza-beauty-space/images/service-makeup-bridal.jpg",
          "caption": "Свадебный образ от Top Master Ayza Ertaeva",
          "displayOrder": 1
        },
        {
          "id": "work-2",
          "imageUrl": "/tenants/ayza-beauty-space/images/service-hair-bridal.jpg",
          "caption": "Свадебная прическа и текстурные локоны",
          "displayOrder": 2
        },
        {
          "id": "work-3",
          "imageUrl": "/tenants/ayza-beauty-space/images/service-manicure-extension.jpg",
          "caption": "Наращивание ногтей на верхних формах",
          "displayOrder": 3
        },
        {
          "id": "work-4",
          "imageUrl": "/tenants/ayza-beauty-space/images/service-pedicure-gel.jpg",
          "caption": "Педикюр с гелевым покрытием",
          "displayOrder": 4
        },
        {
          "id": "work-5",
          "imageUrl": "/tenants/ayza-beauty-space/images/service-makeup-evening.jpg",
          "caption": "Вечерний макияж и выразительный взгляд",
          "displayOrder": 5
        },
        {
          "id": "work-6",
          "imageUrl": "/tenants/ayza-beauty-space/images/service-hair-evening.jpg",
          "caption": "Вечерняя укладка и локоны",
          "displayOrder": 6
        },
        {
          "id": "work-7",
          "imageUrl": "/tenants/ayza-beauty-space/images/service-brows.png",
          "caption": "Архитектура и окрашивание бровей",
          "displayOrder": 7
        },
        {
          "id": "work-8",
          "imageUrl": "/tenants/ayza-beauty-space/images/service-hair-styling.jpg",
          "caption": "Объемная укладка волос",
          "displayOrder": 8
        },
        {
          "id": "work-9",
          "imageUrl": "/tenants/ayza-beauty-space/images/service-manicure-polish.jpg",
          "caption": "Маникюр со стойким покрытием",
          "displayOrder": 9
        },
        {
          "id": "work-10",
          "imageUrl": "/tenants/ayza-beauty-space/images/service-pedicure-classic.jpg",
          "caption": "Аппаратная обработка стоп и пальчиков",
          "displayOrder": 10
        },
        {
          "id": "work-11",
          "imageUrl": "/tenants/ayza-beauty-space/images/service-lashes-classic.jpg",
          "caption": "Классическое наращивание ресниц",
          "displayOrder": 11
        },
        {
          "id": "work-12",
          "imageUrl": "/tenants/ayza-beauty-space/images/service-makeup-day.jpg",
          "caption": "Дневной макияж и естественное сияние",
          "displayOrder": 12
        },
        {
          "id": "work-13",
          "imageUrl": "/tenants/ayza-beauty-space/images/service-manicure-classic.jpg",
          "caption": "Чистый гигиенический маникюр",
          "displayOrder": 13
        },
        {
          "id": "work-14",
          "imageUrl": "/tenants/ayza-beauty-space/images/service-pedicure-spa.jpg",
          "caption": "СПА-уход для ног и парафинотерапия",
          "displayOrder": 14
        }
      ]
    }
  },
  "lumi-nail-studio": {
    "id": "11111111-1111-4111-8111-111111111111",
    "slug": "lumi-nail-studio",
    "name": "DEMO BEAUTY STUDIO",
    "status": "published",
    "tagline": "Премиальная эстетика, безупречный маникюр и забота о деталях",
    "phone": "+7 (495) 780-11-22",
    "address": "ул. Большая Никитская, 14/2",
    "city": "Москва",
    "timezone": "Europe/Moscow",
    "currency": "RUB",
    "minBookingNoticeMin": 60,
    "maxBookingHorizonDays": 30,
    "cancellationDeadlineHours": 4,
    "instructions": "В студии действует комплиментарный бар: specialty-кофе, матча и авторские лимонады. Пожалуйста, сообщите администратору о наличии аллергических реакций.",
    "theme": {
      "accentColor": "#FFFFFF",
      "secondaryAccentColor": "#E2E2E8",
      "bgColor": "#050507",
      "cardBgColor": "#0D0D11",
      "borderColor": "rgba(255, 255, 255, 0.12)",
      "textColor": "#FFFFFF",
      "mutedColor": "#8E8E93",
      "fontHeading": "'Playfair Display', Georgia, serif",
      "fontBody": "'Inter', -apple-system, sans-serif"
    },
    "infoCards": [
      {
        "id": "card-1",
        "title": "Студия сейчас открыта до 22:00",
        "description": "Принимаем онлайн-записи на сегодня и завтра без выходных",
        "icon": "Clock"
      },
      {
        "id": "card-2",
        "title": "100% Стерильно по СанПиН",
        "description": "3-этапная стерилизация в сухожаре ГП-20, крафт-пакет вскрывается при вас",
        "icon": "ShieldCheck"
      },
      {
        "id": "card-3",
        "title": "Гарантия 7 дней",
        "description": "Бесплатная коррекция покрытия при любых сколах или отслойках",
        "icon": "Diamond"
      }
    ],
    "businessHours": [
      {
        "dayOfWeek": 0,
        "openTime": "10:00",
        "closeTime": "21:00",
        "isClosed": false
      },
      {
        "dayOfWeek": 1,
        "openTime": "10:00",
        "closeTime": "22:00",
        "isClosed": false
      },
      {
        "dayOfWeek": 2,
        "openTime": "10:00",
        "closeTime": "22:00",
        "isClosed": false
      },
      {
        "dayOfWeek": 3,
        "openTime": "10:00",
        "closeTime": "22:00",
        "isClosed": false
      },
      {
        "dayOfWeek": 4,
        "openTime": "10:00",
        "closeTime": "22:00",
        "isClosed": false
      },
      {
        "dayOfWeek": 5,
        "openTime": "10:00",
        "closeTime": "22:00",
        "isClosed": false
      },
      {
        "dayOfWeek": 6,
        "openTime": "10:00",
        "closeTime": "21:00",
        "isClosed": false
      }
    ],
    "workplaces": [
      {
        "id": "10000000-0000-4000-8000-000000000001",
        "name": "Маникюрный стол Lumi Gold",
        "type": "MANICURE_DESK",
        "isActive": true
      },
      {
        "id": "10000000-0000-4000-8000-000000000002",
        "name": "Маникюрный стол Lumi Velvet",
        "type": "MANICURE_DESK",
        "isActive": true
      },
      {
        "id": "10000000-0000-4000-8000-000000000003",
        "name": "Педикюрный трон Lumi Spa",
        "type": "PEDICURE_CHAIR",
        "isActive": true
      }
    ],
    "categories": [
      {
        "id": "10000000-0000-4000-8000-000000000010",
        "name": "Маникюр",
        "displayOrder": 1,
        "isActive": true
      },
      {
        "id": "10000000-0000-4000-8000-000000000020",
        "name": "Педикюр",
        "displayOrder": 2,
        "isActive": true
      },
      {
        "id": "10000000-0000-4000-8000-000000000030",
        "name": "Укрепление & Наращивание",
        "displayOrder": 3,
        "isActive": true
      },
      {
        "id": "10000000-0000-4000-8000-000000000040",
        "name": "Дизайн & Уход",
        "displayOrder": 4,
        "isActive": true
      }
    ],
    "services": [
      {
        "id": "10000000-0000-4000-8000-000000000101",
        "categoryId": "10000000-0000-4000-8000-000000000010",
        "name": "Комплекс «Маникюр + гель-лак + выравнивание»",
        "description": "Снятие старого покрытия, комбинированная обработка кутикулы, архитектурное выравнивание базой Luxio/Kodi, стойкое покрытие под кутикулу, увлажняющее масло.",
        "price": 3200,
        "durationMin": 90,
        "bufferAfterMin": 15,
        "requiredWorkplaceType": "MANICURE_DESK",
        "imageUrl": "https://images.unsplash.com/photo-1604654894610-df63bc536371?auto=format&fit=crop&w=600&q=80",
        "displayOrder": 1,
        "isActive": true
      },
      {
        "id": "10000000-0000-4000-8000-000000000102",
        "categoryId": "10000000-0000-4000-8000-000000000010",
        "name": "Атравматичный пилочный маникюр без покрытия",
        "description": "Мягкая безаппаратная техника с использованием индивидуальных одноразовых пилок. Идеальная бархатная кутикула без риска пропилов.",
        "price": 2500,
        "durationMin": 60,
        "bufferAfterMin": 15,
        "requiredWorkplaceType": "MANICURE_DESK",
        "imageUrl": "https://images.unsplash.com/photo-1632345031435-8727f6897d53?auto=format&fit=crop&w=600&q=80",
        "displayOrder": 2,
        "isActive": true
      },
      {
        "id": "10000000-0000-4000-8000-000000000103",
        "categoryId": "10000000-0000-4000-8000-000000000010",
        "name": "Японский эко-маникюр Masura",
        "description": "Оздоравливающая процедура для натуральных ногтей: полировка минеральной пастой с жемчужной крошкой и запечатывание пчелиным воском.",
        "price": 2800,
        "durationMin": 60,
        "bufferAfterMin": 15,
        "requiredWorkplaceType": "MANICURE_DESK",
        "imageUrl": "https://images.unsplash.com/photo-1519014816548-bf5fe059798b?auto=format&fit=crop&w=600&q=80",
        "displayOrder": 3,
        "isActive": true
      },
      {
        "id": "10000000-0000-4000-8000-000000000104",
        "categoryId": "10000000-0000-4000-8000-000000000020",
        "name": "Эстетический Smart-педикюр с гель-лаком",
        "description": "Инновационная обработка стоп с молекулярным smart-маслом, идеальная гладкость пяток до 4 недель, обработка пальчиков и покрытие гель-лаком.",
        "price": 4200,
        "durationMin": 100,
        "bufferAfterMin": 20,
        "requiredWorkplaceType": "PEDICURE_CHAIR",
        "imageUrl": "https://images.unsplash.com/photo-1519415510236-718bdfcd89c8?auto=format&fit=crop&w=600&q=80",
        "displayOrder": 4,
        "isActive": true
      },
      {
        "id": "10000000-0000-4000-8000-000000000105",
        "categoryId": "10000000-0000-4000-8000-000000000030",
        "name": "Моделирование ногтей гелем / акригелем (длина 1-2)",
        "description": "Создание идеальной миндальной или квадратной формы на нижние/верхние формы с архитектурой натурального ногтя.",
        "price": 4800,
        "durationMin": 120,
        "bufferAfterMin": 15,
        "requiredWorkplaceType": "MANICURE_DESK",
        "imageUrl": "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&w=600&q=80",
        "displayOrder": 5,
        "isActive": true
      }
    ],
    "options": [
      {
        "id": "10000000-0000-4000-8000-000000000201",
        "name": "Снятие покрытия другого мастера",
        "description": "Бережное фрезерное снятие без повреждения дорсального слоя",
        "price": 400,
        "durationMin": 15,
        "bufferAfterMin": 0,
        "displayOrder": 1,
        "isActive": true
      },
      {
        "id": "10000000-0000-4000-8000-000000000202",
        "name": "Укрепление гелем / акриловой пудрой",
        "description": "Создание жесткого каркаса для предотвращения сколов и отслоек на мягких ногтях",
        "price": 700,
        "durationMin": 20,
        "bufferAfterMin": 0,
        "displayOrder": 2,
        "isActive": true
      },
      {
        "id": "10000000-0000-4000-8000-000000000203",
        "name": "Френч / Лунный дизайн (все пальцы)",
        "description": "Идеально выверенная улыбка французского покрытия",
        "price": 900,
        "durationMin": 30,
        "bufferAfterMin": 0,
        "displayOrder": 3,
        "isActive": true
      },
      {
        "id": "10000000-0000-4000-8000-000000000204",
        "name": "Авторский nail-дизайн (1 ноготь)",
        "description": "Градиент, стемпинг, инкрустация кристаллами Swarovski или ручная роспись",
        "price": 250,
        "durationMin": 10,
        "bufferAfterMin": 0,
        "displayOrder": 4,
        "isActive": true
      },
      {
        "id": "10000000-0000-4000-8000-000000000205",
        "name": "Ремонт / донаращивание треснувшего ногтя (1 шт)",
        "description": "Восстановление параллелей или угла шелком/полигелем",
        "price": 300,
        "durationMin": 15,
        "bufferAfterMin": 0,
        "displayOrder": 5,
        "isActive": true
      }
    ],
    "masters": [
      {
        "id": "10000000-0000-4000-8000-000000000301",
        "name": "Алёна Смирнова",
        "title": "Топ-мастер, инструктор Lumi",
        "bio": "Опыт 7 лет. Победитель чемпионата Nail Aesthetic Pro. Мастер тонких торцов и безукоризненной формы.",
        "avatarUrl": "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80",
        "rating": 5,
        "reviewsCount": 214,
        "serviceIds": [
          "10000000-0000-4000-8000-000000000101",
          "10000000-0000-4000-8000-000000000102",
          "10000000-0000-4000-8000-000000000103",
          "10000000-0000-4000-8000-000000000105"
        ],
        "schedule": [
          {
            "dayOfWeek": 0,
            "startTime": "10:00",
            "endTime": "21:00",
            "isDayOff": false,
            "breaks": []
          },
          {
            "dayOfWeek": 1,
            "startTime": "10:00",
            "endTime": "21:00",
            "isDayOff": false,
            "breaks": []
          },
          {
            "dayOfWeek": 2,
            "startTime": "10:00",
            "endTime": "21:00",
            "isDayOff": false,
            "breaks": []
          },
          {
            "dayOfWeek": 3,
            "startTime": "10:00",
            "endTime": "21:00",
            "isDayOff": false,
            "breaks": []
          },
          {
            "dayOfWeek": 4,
            "startTime": "10:00",
            "endTime": "21:00",
            "isDayOff": false,
            "breaks": []
          },
          {
            "dayOfWeek": 5,
            "startTime": "10:00",
            "endTime": "21:00",
            "isDayOff": false,
            "breaks": []
          },
          {
            "dayOfWeek": 6,
            "startTime": "10:00",
            "endTime": "21:00",
            "isDayOff": true,
            "breaks": []
          }
        ],
        "breaks": [],
        "displayOrder": 1,
        "isActive": true
      },
      {
        "id": "10000000-0000-4000-8000-000000000302",
        "name": "Виктория Ким",
        "title": "Ведущий стилист ногтевого сервиса",
        "bio": "Опыт 5 лет. Скоростной премиум-маникюр за 60 минут без потери качества. Эксперт по сложным дизайнам.",
        "avatarUrl": "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=400&q=80",
        "rating": 4.97,
        "reviewsCount": 168,
        "serviceIds": [
          "10000000-0000-4000-8000-000000000101",
          "10000000-0000-4000-8000-000000000102",
          "10000000-0000-4000-8000-000000000104"
        ],
        "schedule": [
          {
            "dayOfWeek": 0,
            "startTime": "11:00",
            "endTime": "22:00",
            "isDayOff": false,
            "breaks": []
          },
          {
            "dayOfWeek": 1,
            "startTime": "11:00",
            "endTime": "22:00",
            "isDayOff": true,
            "breaks": []
          },
          {
            "dayOfWeek": 2,
            "startTime": "11:00",
            "endTime": "22:00",
            "isDayOff": false,
            "breaks": []
          },
          {
            "dayOfWeek": 3,
            "startTime": "11:00",
            "endTime": "22:00",
            "isDayOff": false,
            "breaks": []
          },
          {
            "dayOfWeek": 4,
            "startTime": "11:00",
            "endTime": "22:00",
            "isDayOff": false,
            "breaks": []
          },
          {
            "dayOfWeek": 5,
            "startTime": "11:00",
            "endTime": "22:00",
            "isDayOff": false,
            "breaks": []
          },
          {
            "dayOfWeek": 6,
            "startTime": "11:00",
            "endTime": "22:00",
            "isDayOff": false,
            "breaks": []
          }
        ],
        "breaks": [],
        "displayOrder": 2,
        "isActive": true
      },
      {
        "id": "10000000-0000-4000-8000-000000000303",
        "name": "Екатерина Морозова",
        "title": "Мастер маникюра и эстетической подологии",
        "bio": "Опыт 6 лет. Медицинское образование. Деликатное решение проблем онихолизиса, трещин и врастающих углов.",
        "avatarUrl": "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=400&q=80",
        "rating": 4.95,
        "reviewsCount": 139,
        "serviceIds": [
          "10000000-0000-4000-8000-000000000101",
          "10000000-0000-4000-8000-000000000102",
          "10000000-0000-4000-8000-000000000104"
        ],
        "schedule": [
          {
            "dayOfWeek": 0,
            "startTime": "10:00",
            "endTime": "20:00",
            "isDayOff": false,
            "breaks": []
          },
          {
            "dayOfWeek": 1,
            "startTime": "10:00",
            "endTime": "20:00",
            "isDayOff": false,
            "breaks": []
          },
          {
            "dayOfWeek": 2,
            "startTime": "10:00",
            "endTime": "20:00",
            "isDayOff": true,
            "breaks": []
          },
          {
            "dayOfWeek": 3,
            "startTime": "10:00",
            "endTime": "20:00",
            "isDayOff": false,
            "breaks": []
          },
          {
            "dayOfWeek": 4,
            "startTime": "10:00",
            "endTime": "20:00",
            "isDayOff": false,
            "breaks": []
          },
          {
            "dayOfWeek": 5,
            "startTime": "10:00",
            "endTime": "20:00",
            "isDayOff": false,
            "breaks": []
          },
          {
            "dayOfWeek": 6,
            "startTime": "10:00",
            "endTime": "20:00",
            "isDayOff": false,
            "breaks": []
          }
        ],
        "breaks": [],
        "displayOrder": 3,
        "isActive": true
      }
    ],
    "assets": {
      "logo": "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&w=200&q=80",
      "hero": "https://images.unsplash.com/photo-1560066984-138dadb4c035?auto=format&fit=crop&w=1600&q=85",
      "gallery": [
        "https://images.unsplash.com/photo-1604654894610-df63bc536371?auto=format&fit=crop&w=800&q=80",
        "https://images.unsplash.com/photo-1632345031435-8727f6897d53?auto=format&fit=crop&w=800&q=80",
        "https://images.unsplash.com/photo-1519014816548-bf5fe059798b?auto=format&fit=crop&w=800&q=80",
        "https://images.unsplash.com/photo-1571290274554-6a2eaa771e5f?auto=format&fit=crop&w=800&q=80",
        "https://images.unsplash.com/photo-1566113519662-7807a42cc50d?auto=format&fit=crop&w=800&q=80",
        "https://images.unsplash.com/photo-1519415510236-718bdfcd89c8?auto=format&fit=crop&w=800&q=80"
      ],
      "galleryItems": [
        {
          "id": "work-1",
          "imageUrl": "https://images.unsplash.com/photo-1604654894610-df63bc536371?auto=format&fit=crop&w=800&q=80",
          "caption": "Chanel Noire — глянец глубокого черного",
          "displayOrder": 1
        },
        {
          "id": "work-2",
          "imageUrl": "https://images.unsplash.com/photo-1632345031435-8727f6897d53?auto=format&fit=crop&w=800&q=80",
          "caption": "Французский маникюр с молочным камуфляжем",
          "displayOrder": 2
        },
        {
          "id": "work-3",
          "imageUrl": "https://images.unsplash.com/photo-1519014816548-bf5fe059798b?auto=format&fit=crop&w=800&q=80",
          "caption": "Японский эко-уход Masura и зеркальный блеск",
          "displayOrder": 3
        },
        {
          "id": "work-4",
          "imageUrl": "https://images.unsplash.com/photo-1571290274554-6a2eaa771e5f?auto=format&fit=crop&w=800&q=80",
          "caption": "Микро-френч и серебряные линии",
          "displayOrder": 4
        },
        {
          "id": "work-5",
          "imageUrl": "https://images.unsplash.com/photo-1566113519662-7807a42cc50d?auto=format&fit=crop&w=800&q=80",
          "caption": "Haute Couture — подиумный минимализм",
          "displayOrder": 5
        },
        {
          "id": "work-6",
          "imageUrl": "https://images.unsplash.com/photo-1519415510236-718bdfcd89c8?auto=format&fit=crop&w=800&q=80",
          "caption": "Эстетический Smart-педикюр СПА",
          "displayOrder": 6
        }
      ]
    }
  }
};

export function getTenantBySlug(slug: string): BusinessConfig | undefined {
  return TENANTS_REGISTRY[slug];
}
