// Auto-generated by tenant-publish.ts. DO NOT EDIT DIRECTLY.
import type { BusinessConfig } from '../../scripts/schema';

export const TENANTS_REGISTRY: Record<string, BusinessConfig> = {
  "aura-nail-bar": {
    "id": "22222222-2222-4222-8222-222222222222",
    "slug": "aura-nail-bar",
    "name": "AURA NAIL BAR",
    "status": "sample",
    "tagline": "SoHo Express Luxury Manicure & Conceptual Nail Bar",
    "phone": "+1 (212) 480-9944",
    "address": "548 Broadway, SoHo",
    "city": "New York, NY",
    "timezone": "America/New_York",
    "currency": "USD",
    "minBookingNoticeMin": 45,
    "maxBookingHorizonDays": 21,
    "cancellationDeadlineHours": 3,
    "instructions": "Located on the 2nd floor of SoHo Creative Lofts. Express online booking, high-speed Wi-Fi, and complimentary artisanal iced drinks to-go.",
    "theme": {
      "accentColor": "#2DD4BF",
      "secondaryAccentColor": "#F5EBE0",
      "bgColor": "#0F172A",
      "cardBgColor": "#1E293B",
      "borderColor": "rgba(255, 255, 255, 0.1)",
      "textColor": "#F8FAFC",
      "mutedColor": "#94A3B8",
      "fontHeading": "Inter, sans-serif",
      "fontBody": "Inter, sans-serif"
    },
    "infoCards": [
      {
        "id": "card-1",
        "title": "SoHo Open Daily",
        "description": "Express manicure & pedicure appointments from 9:00 AM to 9:00 PM",
        "icon": "Clock"
      },
      {
        "id": "card-2",
        "title": "Speed & Precision",
        "description": "Top Manhattan nail technicians with high-durability builder gel overlays",
        "icon": "Star"
      },
      {
        "id": "card-3",
        "title": "Hospital-Grade Hygiene",
        "description": "100% sterilized instruments & individual disposable tool packs",
        "icon": "ShieldCheck"
      }
    ],
    "businessHours": [
      {
        "dayOfWeek": 0,
        "openTime": "11:00",
        "closeTime": "20:00",
        "isClosed": false
      },
      {
        "dayOfWeek": 1,
        "openTime": "09:00",
        "closeTime": "21:00",
        "isClosed": false
      },
      {
        "dayOfWeek": 2,
        "openTime": "09:00",
        "closeTime": "21:00",
        "isClosed": false
      },
      {
        "dayOfWeek": 3,
        "openTime": "09:00",
        "closeTime": "21:00",
        "isClosed": false
      },
      {
        "dayOfWeek": 4,
        "openTime": "09:00",
        "closeTime": "21:00",
        "isClosed": false
      },
      {
        "dayOfWeek": 5,
        "openTime": "09:00",
        "closeTime": "22:00",
        "isClosed": false
      },
      {
        "dayOfWeek": 6,
        "openTime": "10:00",
        "closeTime": "21:00",
        "isClosed": false
      }
    ],
    "workplaces": [
      {
        "id": "20000000-0000-4000-8000-000000000001",
        "name": "Aura Bar Station 1",
        "type": "MANICURE_DESK",
        "isActive": true
      },
      {
        "id": "20000000-0000-4000-8000-000000000002",
        "name": "Aura Bar Station 2",
        "type": "MANICURE_DESK",
        "isActive": true
      },
      {
        "id": "20000000-0000-4000-8000-000000000003",
        "name": "Podology Spa Capsule",
        "type": "PEDICURE_CHAIR",
        "isActive": true
      }
    ],
    "categories": [
      {
        "id": "20000000-0000-4000-8000-000000000010",
        "name": "Express Manicure",
        "displayOrder": 1,
        "isActive": true
      },
      {
        "id": "20000000-0000-4000-8000-000000000020",
        "name": "Gel & Flash Finish",
        "displayOrder": 2,
        "isActive": true
      },
      {
        "id": "20000000-0000-4000-8000-000000000030",
        "name": "Podology & Pedicure",
        "displayOrder": 3,
        "isActive": true
      }
    ],
    "services": [
      {
        "id": "20000000-0000-4000-8000-000000000101",
        "categoryId": "20000000-0000-4000-8000-000000000010",
        "name": "Express E-File Manicure",
        "description": "Precision dry cuticle cleaning in 40 minutes. Perfect for busy professionals on lunch break.",
        "price": 55,
        "durationMin": 40,
        "bufferAfterMin": 10,
        "requiredWorkplaceType": "MANICURE_DESK",
        "imageUrl": "https://images.unsplash.com/photo-1632345031435-8727f6897d53?auto=format&fit=crop&w=600&q=80",
        "displayOrder": 1,
        "isActive": true
      },
      {
        "id": "20000000-0000-4000-8000-000000000102",
        "categoryId": "20000000-0000-4000-8000-000000000020",
        "name": "Flash Reflective Gel Manicure",
        "description": "Clean cuticle detailing followed by hyper-reflective glitter flash gel with diamond gloss.",
        "price": 75,
        "durationMin": 60,
        "bufferAfterMin": 15,
        "requiredWorkplaceType": "MANICURE_DESK",
        "imageUrl": "https://images.unsplash.com/photo-1604654894610-df63bc536371?auto=format&fit=crop&w=600&q=80",
        "displayOrder": 2,
        "isActive": true
      },
      {
        "id": "20000000-0000-4000-8000-000000000103",
        "categoryId": "20000000-0000-4000-8000-000000000030",
        "name": "Aura Smart Podology Pedicure",
        "description": "Disc podology smoothing treatment, calluses renewal, and long-wear gel coat.",
        "price": 90,
        "durationMin": 75,
        "bufferAfterMin": 15,
        "requiredWorkplaceType": "PEDICURE_CHAIR",
        "imageUrl": "https://images.unsplash.com/photo-1519415510236-718bdfcd89c8?auto=format&fit=crop&w=600&q=80",
        "displayOrder": 3,
        "isActive": true
      }
    ],
    "options": [
      {
        "id": "20000000-0000-4000-8000-000000000201",
        "name": "Gel Removal",
        "description": "Safe e-file polish removal",
        "price": 15,
        "durationMin": 15,
        "bufferAfterMin": 0,
        "displayOrder": 1,
        "isActive": true
      },
      {
        "id": "20000000-0000-4000-8000-000000000202",
        "name": "French Tips Accent",
        "description": "Minimalist white or colored French line",
        "price": 25,
        "durationMin": 15,
        "bufferAfterMin": 0,
        "displayOrder": 2,
        "isActive": true
      }
    ],
    "masters": [
      {
        "id": "20000000-0000-4000-8000-000000000301",
        "name": "Maya Sterling",
        "title": "Lead Speed Stylist",
        "bio": "4+ years experience. Quick, meticulous, high durability builder overlays.",
        "avatarUrl": "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=400&q=80",
        "rating": 4.92,
        "reviewsCount": 88,
        "serviceIds": [
          "20000000-0000-4000-8000-000000000101",
          "20000000-0000-4000-8000-000000000102"
        ],
        "schedule": [
          {
            "dayOfWeek": 0,
            "startTime": "11:00",
            "endTime": "20:00",
            "isDayOff": false,
            "breaks": []
          },
          {
            "dayOfWeek": 1,
            "startTime": "09:00",
            "endTime": "21:00",
            "isDayOff": false,
            "breaks": []
          },
          {
            "dayOfWeek": 2,
            "startTime": "09:00",
            "endTime": "21:00",
            "isDayOff": false,
            "breaks": []
          },
          {
            "dayOfWeek": 3,
            "startTime": "09:00",
            "endTime": "21:00",
            "isDayOff": false,
            "breaks": []
          },
          {
            "dayOfWeek": 4,
            "startTime": "09:00",
            "endTime": "21:00",
            "isDayOff": false,
            "breaks": []
          },
          {
            "dayOfWeek": 5,
            "startTime": "09:00",
            "endTime": "22:00",
            "isDayOff": false,
            "breaks": []
          },
          {
            "dayOfWeek": 6,
            "startTime": "10:00",
            "endTime": "21:00",
            "isDayOff": false,
            "breaks": []
          }
        ],
        "breaks": [],
        "displayOrder": 1,
        "isActive": true
      }
    ],
    "assets": {
      "logo": "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&w=200&q=80",
      "hero": "https://images.unsplash.com/photo-1560066984-138dadb4c035?auto=format&fit=crop&w=1600&q=85",
      "gallery": [
        "https://images.unsplash.com/photo-1604654894610-df63bc536371?auto=format&fit=crop&w=800&q=80",
        "https://images.unsplash.com/photo-1632345031435-8727f6897d53?auto=format&fit=crop&w=800&q=80"
      ],
      "galleryItems": []
    }
  },
  "lumi-nail-studio": {
    "id": "11111111-1111-4111-8111-111111111111",
    "slug": "lumi-nail-studio",
    "name": "LUMI NAIL ATELIER",
    "status": "published",
    "tagline": "Beverly Hills Haute Nail Atelier & Bespoke Care",
    "phone": "+1 (310) 843-9820",
    "address": "9520 Wilshire Blvd",
    "city": "Beverly Hills, CA",
    "timezone": "America/Los_Angeles",
    "currency": "USD",
    "minBookingNoticeMin": 60,
    "maxBookingHorizonDays": 30,
    "cancellationDeadlineHours": 4,
    "instructions": "Complimentary organic matcha, artisanal espresso, and sparkling rosé bar. Please inform your artist of any allergies or sensitivities upon arrival.",
    "theme": {
      "accentColor": "#FFFFFF",
      "secondaryAccentColor": "#E2E2E8",
      "bgColor": "#050507",
      "cardBgColor": "#0D0D11",
      "borderColor": "rgba(255, 255, 255, 0.12)",
      "textColor": "#FFFFFF",
      "mutedColor": "#8E8E93",
      "fontHeading": "'Playfair Display', Georgia, serif",
      "fontBody": "'Inter', -apple-system, sans-serif"
    },
    "infoCards": [
      {
        "id": "card-1",
        "title": "Open Today until 9:00 PM",
        "description": "Accepting same-day & advance online bookings 7 days a week",
        "icon": "Clock"
      },
      {
        "id": "card-2",
        "title": "Hospital-Grade Autoclave Sterilization",
        "description": "100% sterile dry-heat & ultrasonic sanitation, sealed pouches opened in front of you",
        "icon": "ShieldCheck"
      },
      {
        "id": "card-3",
        "title": "7-Day Perfection Guarantee",
        "description": "Complimentary touch-up & repair for any unexpected chip or peel",
        "icon": "Diamond"
      }
    ],
    "businessHours": [
      {
        "dayOfWeek": 0,
        "openTime": "10:00",
        "closeTime": "21:00",
        "isClosed": false
      },
      {
        "dayOfWeek": 1,
        "openTime": "10:00",
        "closeTime": "21:00",
        "isClosed": false
      },
      {
        "dayOfWeek": 2,
        "openTime": "10:00",
        "closeTime": "21:00",
        "isClosed": false
      },
      {
        "dayOfWeek": 3,
        "openTime": "10:00",
        "closeTime": "21:00",
        "isClosed": false
      },
      {
        "dayOfWeek": 4,
        "openTime": "10:00",
        "closeTime": "21:00",
        "isClosed": false
      },
      {
        "dayOfWeek": 5,
        "openTime": "10:00",
        "closeTime": "21:00",
        "isClosed": false
      },
      {
        "dayOfWeek": 6,
        "openTime": "10:00",
        "closeTime": "21:00",
        "isClosed": false
      }
    ],
    "workplaces": [
      {
        "id": "10000000-0000-4000-8000-000000000001",
        "name": "Manicure Suite Lumi Gold",
        "type": "MANICURE_DESK",
        "isActive": true
      },
      {
        "id": "10000000-0000-4000-8000-000000000002",
        "name": "Manicure Suite Lumi Velvet",
        "type": "MANICURE_DESK",
        "isActive": true
      },
      {
        "id": "10000000-0000-4000-8000-000000000003",
        "name": "Spa Pedicure Throne Lumi Private",
        "type": "PEDICURE_CHAIR",
        "isActive": true
      }
    ],
    "categories": [
      {
        "id": "10000000-0000-4000-8000-000000000010",
        "name": "Manicure & Gel",
        "displayOrder": 1,
        "isActive": true
      },
      {
        "id": "10000000-0000-4000-8000-000000000020",
        "name": "Pedicure & Foot Care",
        "displayOrder": 2,
        "isActive": true
      },
      {
        "id": "10000000-0000-4000-8000-000000000030",
        "name": "Structure & Extensions",
        "displayOrder": 3,
        "isActive": true
      },
      {
        "id": "10000000-0000-4000-8000-000000000040",
        "name": "Nail Art & Spa Care",
        "displayOrder": 4,
        "isActive": true
      }
    ],
    "services": [
      {
        "id": "10000000-0000-4000-8000-000000000101",
        "categoryId": "10000000-0000-4000-8000-000000000010",
        "name": "Signature Russian Gel Manicure",
        "description": "Meticulous e-file dry cuticle detailing, architectural builder base alignment with Japanese gels, long-wear high gloss finish under cuticle.",
        "price": 95,
        "durationMin": 75,
        "bufferAfterMin": 15,
        "requiredWorkplaceType": "MANICURE_DESK",
        "imageUrl": "https://images.unsplash.com/photo-1604654894610-df63bc536371?auto=format&fit=crop&w=600&q=80",
        "displayOrder": 1,
        "isActive": true
      },
      {
        "id": "10000000-0000-4000-8000-000000000102",
        "categoryId": "10000000-0000-4000-8000-000000000010",
        "name": "Clean Bare Nail E-File Manicure",
        "description": "Non-toxic bare nail rejuvenation, gentle e-file dry cuticle contouring, organic keratin strengthener, warm botanical oil massage.",
        "price": 75,
        "durationMin": 50,
        "bufferAfterMin": 15,
        "requiredWorkplaceType": "MANICURE_DESK",
        "imageUrl": "https://images.unsplash.com/photo-1632345031435-8727f6897d53?auto=format&fit=crop&w=600&q=80",
        "displayOrder": 2,
        "isActive": true
      },
      {
        "id": "10000000-0000-4000-8000-000000000103",
        "categoryId": "10000000-0000-4000-8000-000000000010",
        "name": "Japanese Eco-Gloss Manicure (P.Shine)",
        "description": "Holistic organic detox ritual with sea pearl minerals, diatomaceous clay paste, and organic beeswax sealing for brilliant healthy shine.",
        "price": 85,
        "durationMin": 60,
        "bufferAfterMin": 15,
        "requiredWorkplaceType": "MANICURE_DESK",
        "imageUrl": "https://images.unsplash.com/photo-1519014816548-bf5fe059798b?auto=format&fit=crop&w=600&q=80",
        "displayOrder": 3,
        "isActive": true
      },
      {
        "id": "10000000-0000-4000-8000-000000000104",
        "categoryId": "10000000-0000-4000-8000-000000000020",
        "name": "Smart Wellness Spa Pedicure & Gel",
        "description": "Smart podological disc heel smoothing with molecular oils, exfoliating peel, warm hydration treatment, and long-wear gel color.",
        "price": 115,
        "durationMin": 90,
        "bufferAfterMin": 15,
        "requiredWorkplaceType": "PEDICURE_CHAIR",
        "imageUrl": "https://images.unsplash.com/photo-1519415510236-718bdfcd89c8?auto=format&fit=crop&w=600&q=80",
        "displayOrder": 4,
        "isActive": true
      },
      {
        "id": "10000000-0000-4000-8000-000000000105",
        "categoryId": "10000000-0000-4000-8000-000000000030",
        "name": "Aprés Gel-X / Sculpted Hard Gel Extensions",
        "description": "Custom-sculpted lightweight length with premium durability, bespoke shape (almond, square, or coffin), and high-gloss gel finish.",
        "price": 145,
        "durationMin": 105,
        "bufferAfterMin": 15,
        "requiredWorkplaceType": "MANICURE_DESK",
        "imageUrl": "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&w=600&q=80",
        "displayOrder": 5,
        "isActive": true
      }
    ],
    "options": [
      {
        "id": "10000000-0000-4000-8000-000000000201",
        "name": "Foreign Gel Removal",
        "description": "Gentle e-file removal of gel or acrylic from another salon without damaging the nail bed",
        "price": 15,
        "durationMin": 15,
        "bufferAfterMin": 0,
        "displayOrder": 1,
        "isActive": true
      },
      {
        "id": "10000000-0000-4000-8000-000000000202",
        "name": "Hard Gel / Structure Reinforcement",
        "description": "Reinforced apex architecture for soft or brittle nails to prevent breaking",
        "price": 25,
        "durationMin": 15,
        "bufferAfterMin": 0,
        "displayOrder": 2,
        "isActive": true
      },
      {
        "id": "10000000-0000-4000-8000-000000000203",
        "name": "French / Glazed Donut Chrome Finish",
        "description": "Precision French smile line, pearl chrome glaze, or cat-eye magnetic velvet finish",
        "price": 30,
        "durationMin": 25,
        "bufferAfterMin": 0,
        "displayOrder": 3,
        "isActive": true
      },
      {
        "id": "10000000-0000-4000-8000-000000000204",
        "name": "Bespoke Accent Nail Art (per nail)",
        "description": "Hand-painted minimalist line art, 3D chrome accents, or Swarovski crystal placement",
        "price": 10,
        "durationMin": 10,
        "bufferAfterMin": 0,
        "displayOrder": 4,
        "isActive": true
      },
      {
        "id": "10000000-0000-4000-8000-000000000205",
        "name": "Single Nail Repair / Rebuild",
        "description": "Seamless repair of a chipped edge or broken corner using polygel or silk",
        "price": 12,
        "durationMin": 10,
        "bufferAfterMin": 0,
        "displayOrder": 5,
        "isActive": true
      }
    ],
    "masters": [
      {
        "id": "10000000-0000-4000-8000-000000000301",
        "name": "Alena Vance",
        "title": "Master Artist & Lead Educator",
        "bio": "7+ years experience. International Nail Aesthetic Pro winner. Renowned for impeccable micro-cuticle precision and architectural builder gels.",
        "avatarUrl": "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80",
        "rating": 5,
        "reviewsCount": 214,
        "serviceIds": [
          "10000000-0000-4000-8000-000000000101",
          "10000000-0000-4000-8000-000000000102",
          "10000000-0000-4000-8000-000000000103",
          "10000000-0000-4000-8000-000000000105"
        ],
        "schedule": [
          {
            "dayOfWeek": 0,
            "startTime": "10:00",
            "endTime": "21:00",
            "isDayOff": false,
            "breaks": []
          },
          {
            "dayOfWeek": 1,
            "startTime": "10:00",
            "endTime": "21:00",
            "isDayOff": false,
            "breaks": []
          },
          {
            "dayOfWeek": 2,
            "startTime": "10:00",
            "endTime": "21:00",
            "isDayOff": false,
            "breaks": []
          },
          {
            "dayOfWeek": 3,
            "startTime": "10:00",
            "endTime": "21:00",
            "isDayOff": false,
            "breaks": []
          },
          {
            "dayOfWeek": 4,
            "startTime": "10:00",
            "endTime": "21:00",
            "isDayOff": false,
            "breaks": []
          },
          {
            "dayOfWeek": 5,
            "startTime": "10:00",
            "endTime": "21:00",
            "isDayOff": false,
            "breaks": []
          },
          {
            "dayOfWeek": 6,
            "startTime": "10:00",
            "endTime": "21:00",
            "isDayOff": true,
            "breaks": []
          }
        ],
        "breaks": [],
        "displayOrder": 1,
        "isActive": true
      },
      {
        "id": "10000000-0000-4000-8000-000000000302",
        "name": "Victoria Kim",
        "title": "Senior Editorial Nail Stylist",
        "bio": "5+ years experience. Runway & editorial specialist. Flawless 60-min Russian manicure and intricate hand-painted nail art.",
        "avatarUrl": "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=400&q=80",
        "rating": 4.97,
        "reviewsCount": 168,
        "serviceIds": [
          "10000000-0000-4000-8000-000000000101",
          "10000000-0000-4000-8000-000000000102",
          "10000000-0000-4000-8000-000000000104"
        ],
        "schedule": [
          {
            "dayOfWeek": 0,
            "startTime": "11:00",
            "endTime": "21:00",
            "isDayOff": false,
            "breaks": []
          },
          {
            "dayOfWeek": 1,
            "startTime": "11:00",
            "endTime": "21:00",
            "isDayOff": true,
            "breaks": []
          },
          {
            "dayOfWeek": 2,
            "startTime": "11:00",
            "endTime": "21:00",
            "isDayOff": false,
            "breaks": []
          },
          {
            "dayOfWeek": 3,
            "startTime": "11:00",
            "endTime": "21:00",
            "isDayOff": false,
            "breaks": []
          },
          {
            "dayOfWeek": 4,
            "startTime": "11:00",
            "endTime": "21:00",
            "isDayOff": false,
            "breaks": []
          },
          {
            "dayOfWeek": 5,
            "startTime": "11:00",
            "endTime": "21:00",
            "isDayOff": false,
            "breaks": []
          },
          {
            "dayOfWeek": 6,
            "startTime": "11:00",
            "endTime": "21:00",
            "isDayOff": false,
            "breaks": []
          }
        ],
        "breaks": [],
        "displayOrder": 2,
        "isActive": true
      },
      {
        "id": "10000000-0000-4000-8000-000000000303",
        "name": "Catherine Moreau",
        "title": "Aesthetic Podology Specialist",
        "bio": "6+ years experience with medical podology certification. Expert in restorative foot care, onycholysis, and holistic rejuvenation.",
        "avatarUrl": "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=400&q=80",
        "rating": 4.95,
        "reviewsCount": 139,
        "serviceIds": [
          "10000000-0000-4000-8000-000000000101",
          "10000000-0000-4000-8000-000000000102",
          "10000000-0000-4000-8000-000000000104"
        ],
        "schedule": [
          {
            "dayOfWeek": 0,
            "startTime": "10:00",
            "endTime": "20:00",
            "isDayOff": false,
            "breaks": []
          },
          {
            "dayOfWeek": 1,
            "startTime": "10:00",
            "endTime": "20:00",
            "isDayOff": false,
            "breaks": []
          },
          {
            "dayOfWeek": 2,
            "startTime": "10:00",
            "endTime": "20:00",
            "isDayOff": true,
            "breaks": []
          },
          {
            "dayOfWeek": 3,
            "startTime": "10:00",
            "endTime": "20:00",
            "isDayOff": false,
            "breaks": []
          },
          {
            "dayOfWeek": 4,
            "startTime": "10:00",
            "endTime": "20:00",
            "isDayOff": false,
            "breaks": []
          },
          {
            "dayOfWeek": 5,
            "startTime": "10:00",
            "endTime": "20:00",
            "isDayOff": false,
            "breaks": []
          },
          {
            "dayOfWeek": 6,
            "startTime": "10:00",
            "endTime": "20:00",
            "isDayOff": false,
            "breaks": []
          }
        ],
        "breaks": [],
        "displayOrder": 3,
        "isActive": true
      }
    ],
    "assets": {
      "logo": "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&w=200&q=80",
      "hero": "https://images.unsplash.com/photo-1560066984-138dadb4c035?auto=format&fit=crop&w=1600&q=85",
      "gallery": [
        "https://images.unsplash.com/photo-1604654894610-df63bc536371?auto=format&fit=crop&w=800&q=80",
        "https://images.unsplash.com/photo-1632345031435-8727f6897d53?auto=format&fit=crop&w=800&q=80",
        "https://images.unsplash.com/photo-1519014816548-bf5fe059798b?auto=format&fit=crop&w=800&q=80",
        "https://images.unsplash.com/photo-1571290274554-6a2eaa771e5f?auto=format&fit=crop&w=800&q=80",
        "https://images.unsplash.com/photo-1566113519662-7807a42cc50d?auto=format&fit=crop&w=800&q=80",
        "https://images.unsplash.com/photo-1519415510236-718bdfcd89c8?auto=format&fit=crop&w=800&q=80"
      ],
      "galleryItems": [
        {
          "id": "work-1",
          "imageUrl": "https://images.unsplash.com/photo-1604654894610-df63bc536371?auto=format&fit=crop&w=800&q=80",
          "caption": "Chanel Noire — High Gloss Jet Black",
          "displayOrder": 1
        },
        {
          "id": "work-2",
          "imageUrl": "https://images.unsplash.com/photo-1632345031435-8727f6897d53?auto=format&fit=crop&w=800&q=80",
          "caption": "Milky Glaze French Manicure",
          "displayOrder": 2
        },
        {
          "id": "work-3",
          "imageUrl": "https://images.unsplash.com/photo-1519014816548-bf5fe059798b?auto=format&fit=crop&w=800&q=80",
          "caption": "Japanese Eco-Shine Organic Detox",
          "displayOrder": 3
        },
        {
          "id": "work-4",
          "imageUrl": "https://images.unsplash.com/photo-1571290274554-6a2eaa771e5f?auto=format&fit=crop&w=800&q=80",
          "caption": "Micro-French with Chrome Accents",
          "displayOrder": 4
        },
        {
          "id": "work-5",
          "imageUrl": "https://images.unsplash.com/photo-1566113519662-7807a42cc50d?auto=format&fit=crop&w=800&q=80",
          "caption": "Haute Couture Runway Minimalism",
          "displayOrder": 5
        },
        {
          "id": "work-6",
          "imageUrl": "https://images.unsplash.com/photo-1519415510236-718bdfcd89c8?auto=format&fit=crop&w=800&q=80",
          "caption": "Smart Spa Wellness Pedicure",
          "displayOrder": 6
        }
      ]
    }
  }
};

export function getTenantBySlug(slug: string): BusinessConfig | undefined {
  return TENANTS_REGISTRY[slug];
}
