// Auto-generated by tenant-publish.ts. DO NOT EDIT DIRECTLY.
import type { BusinessConfig } from '../../scripts/schema';

export const TENANTS_REGISTRY: Record<string, BusinessConfig> = {
  "aura-nail-bar": {
    "id": "22222222-2222-4222-8222-222222222222",
    "slug": "aura-nail-bar",
    "name": "AURA NAIL BAR",
    "status": "sample",
    "tagline": "Экспресс-студия маникюра и концептуальный нейл-бар",
    "phone": "+7 (812) 330-99-44",
    "address": "Невский проспект, 78",
    "city": "Санкт-Петербург",
    "timezone": "Europe/Moscow",
    "currency": "RUB",
    "minBookingNoticeMin": 45,
    "maxBookingHorizonDays": 21,
    "cancellationDeadlineHours": 3,
    "instructions": "Студия расположена на 2 этаже арт-пространства. Быстрая запись, высокоскоростной Wi-Fi, напитки to-go.",
    "theme": {
      "accentColor": "#2DD4BF",
      "secondaryAccentColor": "#F5EBE0",
      "bgColor": "#0F172A",
      "cardBgColor": "#1E293B",
      "borderColor": "rgba(255, 255, 255, 0.1)",
      "textColor": "#F8FAFC",
      "mutedColor": "#94A3B8",
      "fontHeading": "Inter, sans-serif",
      "fontBody": "Inter, sans-serif"
    },
    "infoCards": [
      {
        "id": "card-1",
        "title": "Работаем каждый день",
        "description": "С 10:00 до 22:00 без выходных и перерывов",
        "icon": "Clock"
      },
      {
        "id": "card-2",
        "title": "Опытные мастера",
        "description": "Сертифицированные специалисты с опытом от 5 лет",
        "icon": "Star"
      },
      {
        "id": "card-3",
        "title": "Материалы премиум-класса",
        "description": "Безопасные составы, стерилизация по СанПиН в 3 этапа",
        "icon": "ShieldCheck"
      }
    ],
    "businessHours": [
      {
        "dayOfWeek": 0,
        "openTime": "11:00",
        "closeTime": "21:00",
        "isClosed": false
      },
      {
        "dayOfWeek": 1,
        "openTime": "09:00",
        "closeTime": "22:00",
        "isClosed": false
      },
      {
        "dayOfWeek": 2,
        "openTime": "09:00",
        "closeTime": "22:00",
        "isClosed": false
      },
      {
        "dayOfWeek": 3,
        "openTime": "09:00",
        "closeTime": "22:00",
        "isClosed": false
      },
      {
        "dayOfWeek": 4,
        "openTime": "09:00",
        "closeTime": "22:00",
        "isClosed": false
      },
      {
        "dayOfWeek": 5,
        "openTime": "09:00",
        "closeTime": "23:00",
        "isClosed": false
      },
      {
        "dayOfWeek": 6,
        "openTime": "10:00",
        "closeTime": "22:00",
        "isClosed": false
      }
    ],
    "workplaces": [
      {
        "id": "20000000-0000-4000-8000-000000000001",
        "name": "Барная стойка Aura 1",
        "type": "MANICURE_DESK",
        "isActive": true
      },
      {
        "id": "20000000-0000-4000-8000-000000000002",
        "name": "Барная стойка Aura 2",
        "type": "MANICURE_DESK",
        "isActive": true
      },
      {
        "id": "20000000-0000-4000-8000-000000000003",
        "name": "Педикюрная капсула Podology",
        "type": "PEDICURE_CHAIR",
        "isActive": true
      }
    ],
    "categories": [
      {
        "id": "20000000-0000-4000-8000-000000000010",
        "name": "Экспресс-маникюр",
        "displayOrder": 1,
        "isActive": true
      },
      {
        "id": "20000000-0000-4000-8000-000000000020",
        "name": "Покрытие & Дизайн",
        "displayOrder": 2,
        "isActive": true
      },
      {
        "id": "20000000-0000-4000-8000-000000000030",
        "name": "Подология & Педикюр",
        "displayOrder": 3,
        "isActive": true
      }
    ],
    "services": [
      {
        "id": "20000000-0000-4000-8000-000000000101",
        "categoryId": "20000000-0000-4000-8000-000000000010",
        "name": "Скоростной экспресс-маникюр",
        "description": "Чистая аппаратная обработка за 40 минут. Идеально для занятых девушек в обеденный перерыв.",
        "price": 1800,
        "durationMin": 40,
        "bufferAfterMin": 10,
        "requiredWorkplaceType": "MANICURE_DESK",
        "imageUrl": "https://images.unsplash.com/photo-1632345031435-8727f6897d53?auto=format&fit=crop&w=600&q=80",
        "displayOrder": 1,
        "isActive": true
      },
      {
        "id": "20000000-0000-4000-8000-000000000102",
        "categoryId": "20000000-0000-4000-8000-000000000020",
        "name": "Маникюр с сияющим покрытием Flash Gel",
        "description": "Комби-обработка, светоотражающие трендовые базы Flash Disco с глубоким переливом.",
        "price": 2600,
        "durationMin": 70,
        "bufferAfterMin": 15,
        "requiredWorkplaceType": "MANICURE_DESK",
        "imageUrl": "https://images.unsplash.com/photo-1604654894610-df63bc536371?auto=format&fit=crop&w=600&q=80",
        "displayOrder": 2,
        "isActive": true
      },
      {
        "id": "20000000-0000-4000-8000-000000000103",
        "categoryId": "20000000-0000-4000-8000-000000000030",
        "name": "Кислотный экспресс-педикюр KART",
        "description": "Фруктово-ферментативная обработка сложных стоп и натоптышей без лезвий и трещин.",
        "price": 3500,
        "durationMin": 75,
        "bufferAfterMin": 15,
        "requiredWorkplaceType": "PEDICURE_CHAIR",
        "imageUrl": "https://images.unsplash.com/photo-1519415510236-718bdfcd89c8?auto=format&fit=crop&w=600&q=80",
        "displayOrder": 3,
        "isActive": true
      }
    ],
    "options": [
      {
        "id": "20000000-0000-4000-8000-000000000201",
        "name": "Снятие гель-лака",
        "description": "Быстрое снятие твердосплавной фрезой",
        "price": 350,
        "durationMin": 15,
        "bufferAfterMin": 0,
        "displayOrder": 1,
        "isActive": true
      },
      {
        "id": "20000000-0000-4000-8000-000000000202",
        "name": "Глянцевый топ анти-царапины",
        "description": "Сверхстойкий финиш с зеркальным блеском до 5 недель",
        "price": 300,
        "durationMin": 10,
        "bufferAfterMin": 0,
        "displayOrder": 2,
        "isActive": true
      }
    ],
    "masters": [
      {
        "id": "20000000-0000-4000-8000-000000000301",
        "name": "Диана Романова",
        "title": "Мастер-эксперт Aura Bar",
        "bio": "Опыт 4 года. Специалист по скоростному комбо-маникюру и ультра-глянцевому покрытию.",
        "avatarUrl": "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=400&q=80",
        "rating": 4.96,
        "reviewsCount": 112,
        "serviceIds": [
          "20000000-0000-4000-8000-000000000101",
          "20000000-0000-4000-8000-000000000102"
        ],
        "schedule": [
          {
            "dayOfWeek": 0,
            "startTime": "11:00",
            "endTime": "21:00",
            "isDayOff": false,
            "breaks": []
          },
          {
            "dayOfWeek": 1,
            "startTime": "09:00",
            "endTime": "22:00",
            "isDayOff": false,
            "breaks": []
          },
          {
            "dayOfWeek": 2,
            "startTime": "09:00",
            "endTime": "22:00",
            "isDayOff": false,
            "breaks": []
          },
          {
            "dayOfWeek": 3,
            "startTime": "09:00",
            "endTime": "22:00",
            "isDayOff": false,
            "breaks": []
          },
          {
            "dayOfWeek": 4,
            "startTime": "09:00",
            "endTime": "22:00",
            "isDayOff": false,
            "breaks": []
          },
          {
            "dayOfWeek": 5,
            "startTime": "09:00",
            "endTime": "22:00",
            "isDayOff": true,
            "breaks": []
          },
          {
            "dayOfWeek": 6,
            "startTime": "10:00",
            "endTime": "22:00",
            "isDayOff": true,
            "breaks": []
          }
        ],
        "breaks": [],
        "displayOrder": 1,
        "isActive": true
      },
      {
        "id": "20000000-0000-4000-8000-000000000302",
        "name": "Мария Лазарева",
        "title": "Подолог-эстетист",
        "bio": "Опыт 8 лет. Сложный медицинский педикюр, обработка стопы KART, установка коррекционных систем.",
        "avatarUrl": "https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=400&q=80",
        "rating": 4.99,
        "reviewsCount": 184,
        "serviceIds": [
          "20000000-0000-4000-8000-000000000101",
          "20000000-0000-4000-8000-000000000103"
        ],
        "schedule": [
          {
            "dayOfWeek": 0,
            "startTime": "11:00",
            "endTime": "21:00",
            "isDayOff": true,
            "breaks": []
          },
          {
            "dayOfWeek": 1,
            "startTime": "10:00",
            "endTime": "20:00",
            "isDayOff": false,
            "breaks": []
          },
          {
            "dayOfWeek": 2,
            "startTime": "10:00",
            "endTime": "20:00",
            "isDayOff": false,
            "breaks": []
          },
          {
            "dayOfWeek": 3,
            "startTime": "10:00",
            "endTime": "20:00",
            "isDayOff": false,
            "breaks": []
          },
          {
            "dayOfWeek": 4,
            "startTime": "10:00",
            "endTime": "20:00",
            "isDayOff": false,
            "breaks": []
          },
          {
            "dayOfWeek": 5,
            "startTime": "09:00",
            "endTime": "23:00",
            "isDayOff": false,
            "breaks": []
          },
          {
            "dayOfWeek": 6,
            "startTime": "10:00",
            "endTime": "22:00",
            "isDayOff": false,
            "breaks": []
          }
        ],
        "breaks": [],
        "displayOrder": 2,
        "isActive": true
      }
    ],
    "assets": {
      "logo": "https://images.unsplash.com/photo-1632345031435-8727f6897d53?auto=format&fit=crop&w=150&q=80",
      "hero": "https://images.unsplash.com/photo-1519014816548-bf5fe059798b?auto=format&fit=crop&w=1200&q=80",
      "gallery": [
        "https://images.unsplash.com/photo-1604654894610-df63bc536371?auto=format&fit=crop&w=600&q=80"
      ],
      "galleryItems": []
    }
  },
  "lumi-nail-studio": {
    "id": "11111111-1111-4111-8111-111111111111",
    "slug": "lumi-nail-studio",
    "name": "DEMO BEAUTY STUDIO",
    "status": "published",
    "tagline": "Премиальная эстетика, безупречный маникюр и забота о деталях",
    "phone": "+7 (495) 780-11-22",
    "address": "ул. Большая Никитская, 14/2",
    "city": "Москва",
    "timezone": "Europe/Moscow",
    "currency": "RUB",
    "minBookingNoticeMin": 60,
    "maxBookingHorizonDays": 30,
    "cancellationDeadlineHours": 4,
    "instructions": "В студии действует комплиментарный бар: specialty-кофе, матча и авторские лимонады. Пожалуйста, сообщите администратору о наличии аллергических реакций.",
    "theme": {
      "accentColor": "#D4AF37",
      "secondaryAccentColor": "#F5EBE0",
      "bgColor": "#0D0D11",
      "cardBgColor": "#16161C",
      "borderColor": "rgba(212, 175, 55, 0.15)",
      "textColor": "#FAF8F5",
      "mutedColor": "#8E8E93",
      "fontHeading": "Playfair Display, serif",
      "fontBody": "Inter, sans-serif"
    },
    "infoCards": [
      {
        "id": "card-1",
        "title": "Работаем каждый день",
        "description": "С 10:00 до 22:00 без выходных и перерывов",
        "icon": "Clock"
      },
      {
        "id": "card-2",
        "title": "Опытные мастера",
        "description": "Сертифицированные топ-мастера со стажем от 5 лет",
        "icon": "Sparkle"
      },
      {
        "id": "card-3",
        "title": "Материалы премиум-класса",
        "description": "Luxio, безопасные составы, 3-этапная стерилизация по СанПиН",
        "icon": "ShieldCheck"
      }
    ],
    "businessHours": [
      {
        "dayOfWeek": 0,
        "openTime": "10:00",
        "closeTime": "21:00",
        "isClosed": false
      },
      {
        "dayOfWeek": 1,
        "openTime": "10:00",
        "closeTime": "22:00",
        "isClosed": false
      },
      {
        "dayOfWeek": 2,
        "openTime": "10:00",
        "closeTime": "22:00",
        "isClosed": false
      },
      {
        "dayOfWeek": 3,
        "openTime": "10:00",
        "closeTime": "22:00",
        "isClosed": false
      },
      {
        "dayOfWeek": 4,
        "openTime": "10:00",
        "closeTime": "22:00",
        "isClosed": false
      },
      {
        "dayOfWeek": 5,
        "openTime": "10:00",
        "closeTime": "22:00",
        "isClosed": false
      },
      {
        "dayOfWeek": 6,
        "openTime": "10:00",
        "closeTime": "21:00",
        "isClosed": false
      }
    ],
    "workplaces": [
      {
        "id": "10000000-0000-4000-8000-000000000001",
        "name": "Маникюрный стол Lumi Gold",
        "type": "MANICURE_DESK",
        "isActive": true
      },
      {
        "id": "10000000-0000-4000-8000-000000000002",
        "name": "Маникюрный стол Lumi Velvet",
        "type": "MANICURE_DESK",
        "isActive": true
      },
      {
        "id": "10000000-0000-4000-8000-000000000003",
        "name": "Педикюрный трон Lumi Spa",
        "type": "PEDICURE_CHAIR",
        "isActive": true
      }
    ],
    "categories": [
      {
        "id": "10000000-0000-4000-8000-000000000010",
        "name": "Маникюр",
        "displayOrder": 1,
        "isActive": true
      },
      {
        "id": "10000000-0000-4000-8000-000000000020",
        "name": "Педикюр",
        "displayOrder": 2,
        "isActive": true
      },
      {
        "id": "10000000-0000-4000-8000-000000000030",
        "name": "Укрепление & Наращивание",
        "displayOrder": 3,
        "isActive": true
      },
      {
        "id": "10000000-0000-4000-8000-000000000040",
        "name": "Дизайн & Уход",
        "displayOrder": 4,
        "isActive": true
      }
    ],
    "services": [
      {
        "id": "10000000-0000-4000-8000-000000000101",
        "categoryId": "10000000-0000-4000-8000-000000000010",
        "name": "Комплекс «Маникюр + гель-лак + выравнивание»",
        "description": "Снятие старого покрытия, комбинированная обработка кутикулы, архитектурное выравнивание базой Luxio/Kodi, стойкое покрытие под кутикулу, увлажняющее масло.",
        "price": 3200,
        "durationMin": 90,
        "bufferAfterMin": 15,
        "requiredWorkplaceType": "MANICURE_DESK",
        "imageUrl": "https://images.unsplash.com/photo-1604654894610-df63bc536371?auto=format&fit=crop&w=600&q=80",
        "displayOrder": 1,
        "isActive": true
      },
      {
        "id": "10000000-0000-4000-8000-000000000102",
        "categoryId": "10000000-0000-4000-8000-000000000010",
        "name": "Атравматичный пилочный маникюр без покрытия",
        "description": "Мягкая безаппаратная техника с использованием индивидуальных одноразовых пилок. Идеальная бархатная кутикула без риска пропилов.",
        "price": 2500,
        "durationMin": 60,
        "bufferAfterMin": 15,
        "requiredWorkplaceType": "MANICURE_DESK",
        "imageUrl": "https://images.unsplash.com/photo-1632345031435-8727f6897d53?auto=format&fit=crop&w=600&q=80",
        "displayOrder": 2,
        "isActive": true
      },
      {
        "id": "10000000-0000-4000-8000-000000000103",
        "categoryId": "10000000-0000-4000-8000-000000000010",
        "name": "Японский эко-маникюр Masura",
        "description": "Оздоравливающая процедура для натуральных ногтей: полировка минеральной пастой с жемчужной крошкой и запечатывание пчелиным воском.",
        "price": 2800,
        "durationMin": 60,
        "bufferAfterMin": 15,
        "requiredWorkplaceType": "MANICURE_DESK",
        "imageUrl": "https://images.unsplash.com/photo-1519014816548-bf5fe059798b?auto=format&fit=crop&w=600&q=80",
        "displayOrder": 3,
        "isActive": true
      },
      {
        "id": "10000000-0000-4000-8000-000000000104",
        "categoryId": "10000000-0000-4000-8000-000000000020",
        "name": "Эстетический Smart-педикюр с гель-лаком",
        "description": "Инновационная обработка стоп с молекулярным smart-маслом, идеальная гладкость пяток до 4 недель, обработка пальчиков и покрытие гель-лаком.",
        "price": 4200,
        "durationMin": 100,
        "bufferAfterMin": 20,
        "requiredWorkplaceType": "PEDICURE_CHAIR",
        "imageUrl": "https://images.unsplash.com/photo-1519415510236-718bdfcd89c8?auto=format&fit=crop&w=600&q=80",
        "displayOrder": 4,
        "isActive": true
      },
      {
        "id": "10000000-0000-4000-8000-000000000105",
        "categoryId": "10000000-0000-4000-8000-000000000030",
        "name": "Моделирование ногтей гелем / акригелем (длина 1-2)",
        "description": "Создание идеальной миндальной или квадратной формы на нижние/верхние формы с архитектурой натурального ногтя.",
        "price": 4800,
        "durationMin": 120,
        "bufferAfterMin": 15,
        "requiredWorkplaceType": "MANICURE_DESK",
        "imageUrl": "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&w=600&q=80",
        "displayOrder": 5,
        "isActive": true
      }
    ],
    "options": [
      {
        "id": "10000000-0000-4000-8000-000000000201",
        "name": "Снятие покрытия другого мастера",
        "description": "Бережное фрезерное снятие без повреждения дорсального слоя",
        "price": 400,
        "durationMin": 15,
        "bufferAfterMin": 0,
        "displayOrder": 1,
        "isActive": true
      },
      {
        "id": "10000000-0000-4000-8000-000000000202",
        "name": "Укрепление гелем / акриловой пудрой",
        "description": "Создание жесткого каркаса для предотвращения сколов и отслоек на мягких ногтях",
        "price": 700,
        "durationMin": 20,
        "bufferAfterMin": 0,
        "displayOrder": 2,
        "isActive": true
      },
      {
        "id": "10000000-0000-4000-8000-000000000203",
        "name": "Френч / Лунный дизайн (все пальцы)",
        "description": "Идеально выверенная улыбка французского покрытия",
        "price": 900,
        "durationMin": 30,
        "bufferAfterMin": 0,
        "displayOrder": 3,
        "isActive": true
      },
      {
        "id": "10000000-0000-4000-8000-000000000204",
        "name": "Авторский nail-дизайн (1 ноготь)",
        "description": "Градиент, стемпинг, инкрустация кристаллами Swarovski или ручная роспись",
        "price": 250,
        "durationMin": 10,
        "bufferAfterMin": 0,
        "displayOrder": 4,
        "isActive": true
      },
      {
        "id": "10000000-0000-4000-8000-000000000205",
        "name": "Ремонт / донаращивание треснувшего ногтя (1 шт)",
        "description": "Восстановление параллелей или угла шелком/полигелем",
        "price": 300,
        "durationMin": 15,
        "bufferAfterMin": 0,
        "displayOrder": 5,
        "isActive": true
      }
    ],
    "masters": [
      {
        "id": "10000000-0000-4000-8000-000000000301",
        "name": "Алёна Смирнова",
        "title": "Топ-мастер, инструктор Lumi",
        "bio": "Опыт 7 лет. Победитель чемпионата Nail Aesthetic Pro. Мастер тонких торцов и безукоризненной формы.",
        "avatarUrl": "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80",
        "rating": 5,
        "reviewsCount": 214,
        "serviceIds": [
          "10000000-0000-4000-8000-000000000101",
          "10000000-0000-4000-8000-000000000102",
          "10000000-0000-4000-8000-000000000103",
          "10000000-0000-4000-8000-000000000105"
        ],
        "schedule": [
          {
            "dayOfWeek": 0,
            "startTime": "10:00",
            "endTime": "21:00",
            "isDayOff": false,
            "breaks": []
          },
          {
            "dayOfWeek": 1,
            "startTime": "10:00",
            "endTime": "21:00",
            "isDayOff": false,
            "breaks": []
          },
          {
            "dayOfWeek": 2,
            "startTime": "10:00",
            "endTime": "21:00",
            "isDayOff": false,
            "breaks": []
          },
          {
            "dayOfWeek": 3,
            "startTime": "10:00",
            "endTime": "21:00",
            "isDayOff": false,
            "breaks": []
          },
          {
            "dayOfWeek": 4,
            "startTime": "10:00",
            "endTime": "21:00",
            "isDayOff": false,
            "breaks": []
          },
          {
            "dayOfWeek": 5,
            "startTime": "10:00",
            "endTime": "21:00",
            "isDayOff": false,
            "breaks": []
          },
          {
            "dayOfWeek": 6,
            "startTime": "10:00",
            "endTime": "21:00",
            "isDayOff": true,
            "breaks": []
          }
        ],
        "breaks": [],
        "displayOrder": 1,
        "isActive": true
      },
      {
        "id": "10000000-0000-4000-8000-000000000302",
        "name": "Виктория Ким",
        "title": "Ведущий стилист ногтевого сервиса",
        "bio": "Опыт 5 лет. Скоростной премиум-маникюр за 60 минут без потери качества. Эксперт по сложным дизайнам.",
        "avatarUrl": "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=400&q=80",
        "rating": 4.97,
        "reviewsCount": 168,
        "serviceIds": [
          "10000000-0000-4000-8000-000000000101",
          "10000000-0000-4000-8000-000000000102",
          "10000000-0000-4000-8000-000000000104"
        ],
        "schedule": [
          {
            "dayOfWeek": 0,
            "startTime": "11:00",
            "endTime": "22:00",
            "isDayOff": false,
            "breaks": []
          },
          {
            "dayOfWeek": 1,
            "startTime": "11:00",
            "endTime": "22:00",
            "isDayOff": true,
            "breaks": []
          },
          {
            "dayOfWeek": 2,
            "startTime": "11:00",
            "endTime": "22:00",
            "isDayOff": false,
            "breaks": []
          },
          {
            "dayOfWeek": 3,
            "startTime": "11:00",
            "endTime": "22:00",
            "isDayOff": false,
            "breaks": []
          },
          {
            "dayOfWeek": 4,
            "startTime": "11:00",
            "endTime": "22:00",
            "isDayOff": false,
            "breaks": []
          },
          {
            "dayOfWeek": 5,
            "startTime": "11:00",
            "endTime": "22:00",
            "isDayOff": false,
            "breaks": []
          },
          {
            "dayOfWeek": 6,
            "startTime": "11:00",
            "endTime": "22:00",
            "isDayOff": false,
            "breaks": []
          }
        ],
        "breaks": [],
        "displayOrder": 2,
        "isActive": true
      },
      {
        "id": "10000000-0000-4000-8000-000000000303",
        "name": "Екатерина Морозова",
        "title": "Мастер маникюра и эстетической подологии",
        "bio": "Опыт 6 лет. Медицинское образование. Деликатное решение проблем онихолизиса, трещин и врастающих углов.",
        "avatarUrl": "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=400&q=80",
        "rating": 4.95,
        "reviewsCount": 139,
        "serviceIds": [
          "10000000-0000-4000-8000-000000000101",
          "10000000-0000-4000-8000-000000000102",
          "10000000-0000-4000-8000-000000000104"
        ],
        "schedule": [
          {
            "dayOfWeek": 0,
            "startTime": "10:00",
            "endTime": "20:00",
            "isDayOff": false,
            "breaks": []
          },
          {
            "dayOfWeek": 1,
            "startTime": "10:00",
            "endTime": "20:00",
            "isDayOff": false,
            "breaks": []
          },
          {
            "dayOfWeek": 2,
            "startTime": "10:00",
            "endTime": "20:00",
            "isDayOff": true,
            "breaks": []
          },
          {
            "dayOfWeek": 3,
            "startTime": "10:00",
            "endTime": "20:00",
            "isDayOff": false,
            "breaks": []
          },
          {
            "dayOfWeek": 4,
            "startTime": "10:00",
            "endTime": "20:00",
            "isDayOff": false,
            "breaks": []
          },
          {
            "dayOfWeek": 5,
            "startTime": "10:00",
            "endTime": "20:00",
            "isDayOff": false,
            "breaks": []
          },
          {
            "dayOfWeek": 6,
            "startTime": "10:00",
            "endTime": "20:00",
            "isDayOff": false,
            "breaks": []
          }
        ],
        "breaks": [],
        "displayOrder": 3,
        "isActive": true
      }
    ],
    "assets": {
      "logo": "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&w=150&q=80",
      "hero": "https://images.unsplash.com/photo-1604654894610-df63bc536371?auto=format&fit=crop&w=1200&q=80",
      "gallery": [
        "https://images.unsplash.com/photo-1632345031435-8727f6897d53?auto=format&fit=crop&w=600&q=80",
        "https://images.unsplash.com/photo-1519014816548-bf5fe059798b?auto=format&fit=crop&w=600&q=80",
        "https://images.unsplash.com/photo-1604654894610-df63bc536371?auto=format&fit=crop&w=600&q=80"
      ],
      "galleryItems": [
        {
          "id": "work-1",
          "imageUrl": "https://images.unsplash.com/photo-1632345031435-8727f6897d53?auto=format&fit=crop&w=600&q=80",
          "caption": "Французский маникюр с молочным камуфляжем",
          "displayOrder": 1
        },
        {
          "id": "work-2",
          "imageUrl": "https://images.unsplash.com/photo-1519014816548-bf5fe059798b?auto=format&fit=crop&w=600&q=80",
          "caption": "Японский эко-уход и сияние натуральных ногтей",
          "displayOrder": 2
        },
        {
          "id": "work-3",
          "imageUrl": "https://images.unsplash.com/photo-1604654894610-df63bc536371?auto=format&fit=crop&w=600&q=80",
          "caption": "Авторский nail-арт и золотые акценты",
          "displayOrder": 3
        }
      ]
    }
  }
};

export function getTenantBySlug(slug: string): BusinessConfig | undefined {
  return TENANTS_REGISTRY[slug];
}
